"""Generate the controlled LM3 manufacturing-method and tooling register."""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
import tomllib
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[4]
SOURCE = REPO_ROOT / "lib/templates/trainset-manufacturing-methods.toml"
MANIFEST = (
    REPO_ROOT
    / "design/component-catalogue/catalog/buildable-trainset"
    / "buildable-trainset-manifest.json"
)
OUTPUT_ROOT = REPO_ROOT / "design/component-catalogue/catalog/buildable-trainset"
JSON_OUTPUT = OUTPUT_ROOT / "manufacturing-methods.json"
MARKDOWN_OUTPUT = OUTPUT_ROOT / "manufacturing-methods.md"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_and_validate() -> dict[str, Any]:
    source = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    items = {item["id"]: item for item in manifest["product_items"]}
    source_ids = {reference["id"] for reference in source["source"]}
    method_ids: set[str] = set()
    tooling_ids: set[str] = set()
    covered: set[str] = set()
    for method in source["method"]:
        method_id = str(method["id"])
        if method_id in method_ids:
            raise ValueError(f"duplicate manufacturing method {method_id}")
        method_ids.add(method_id)
        unknown_products = sorted(set(method["product_ids"]) - set(items))
        if unknown_products:
            raise ValueError(f"{method_id} references unknown products {unknown_products}")
        unknown_sources = sorted(set(method["source_ids"]) - source_ids)
        if unknown_sources:
            raise ValueError(f"{method_id} references unknown sources {unknown_sources}")
        for tooling_id in method["tooling_ids"]:
            if tooling_id in tooling_ids:
                raise ValueError(f"tooling ID {tooling_id} is assigned to more than one method")
            tooling_ids.add(str(tooling_id))
        sequences = [int(step["sequence"]) for step in method["steps"]]
        if sequences != sorted(set(sequences)):
            raise ValueError(f"{method_id} step sequence is not unique and increasing")
        elapsed = sum(int(step["planning_minutes"]) for step in method["steps"])
        if elapsed != int(method["planning_cycle_minutes"]):
            raise ValueError(
                f"{method_id} step minutes total {elapsed}, expected "
                f"{method['planning_cycle_minutes']}"
            )
        if not any(bool(step["hold_point"]) for step in method["steps"]):
            raise ValueError(f"{method_id} has no hold point")
        covered.update(str(item_id) for item_id in method["product_ids"])

    uncovered = sorted(set(items) - covered)
    if uncovered:
        raise ValueError(f"manufacturing methods do not cover product rows: {uncovered}")
    return {
        **source,
        "source_file": str(SOURCE.relative_to(REPO_ROOT)),
        "source_sha256": sha256(SOURCE),
        "product_manifest": str(MANIFEST.relative_to(REPO_ROOT)),
        "product_manifest_sha256": sha256(MANIFEST),
        "coverage": {
            "product_rows": len(items),
            "covered_product_rows": len(covered),
            "method_count": len(source["method"]),
            "tooling_count": len(tooling_ids),
            "uncovered_product_ids": [],
        },
    }


def render_markdown(data: dict[str, Any]) -> str:
    coverage = data["coverage"]
    lines = [
        "# LM3 manufacturing methods and tooling",
        "",
        "<!-- Generated by tools/automation/buildable-trainset.sh; do not hand-edit. -->",
        "",
        data["planning_basis"],
        "",
        f"**Release boundary:** {data['release_boundary']}",
        "",
        "| Controlled coverage | Value |",
        "|---|---:|",
        f"| Product rows linked to at least one method | {coverage['covered_product_rows']} / {coverage['product_rows']} |",
        f"| Manufacturing methods | {coverage['method_count']} |",
        f"| Named tooling/fixture families | {coverage['tooling_count']} |",
        "",
        "## Method index",
        "",
        "| Method | Work centre | Crew | Planning cycle | Products | Tooling |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for method in data["method"]:
        lines.append(
            f"| [{method['id']}](#{method['id'].lower()}) — {method['title']} | "
            f"{method['work_center']} | {method['crew_size']} | "
            f"{method['planning_cycle_minutes'] / 60:g} h | "
            f"{len(method['product_ids'])} | {len(method['tooling_ids'])} |"
        )
    for method in data["method"]:
        lines.extend(
            [
                "",
                f"## {method['id']} — {method['title']}",
                "",
                f"- Work centre: {method['work_center']}",
                f"- Crew / planning cycle: {method['crew_size']} people / {method['planning_cycle_minutes'] / 60:g} hours elapsed",
                f"- Product IDs: {', '.join(f'`{value}`' for value in method['product_ids'])}",
                f"- Tooling: {', '.join(f'`{value}`' for value in method['tooling_ids'])}",
                f"- Joining parts: {'; '.join(method['joining_parts'])}",
                f"- Release gate: {method['release_gate']}",
                "",
                "| Seq. | Planning time | Instruction | Hold point |",
                "|---:|---:|---|:---:|",
            ]
        )
        for step in method["steps"]:
            instruction = str(step["instruction"]).replace("|", "\\|")
            lines.append(
                f"| {step['sequence']} — {step['name']} | {step['planning_minutes']} min | "
                f"{instruction} | {'yes' if step['hold_point'] else 'no'} |"
            )
    lines.extend(
        [
            "",
            "## External design references",
            "",
            "These links explain the engineering basis; they are not copied supplier instructions or a substitute for the selected product's current technical datasheet.",
            "",
        ]
    )
    for source in data["source"]:
        lines.append(f"- [{source['title']}]({source['url']}) — {source['use']}")
    lines.extend(
        [
            "",
            "## Controlled inputs",
            "",
            f"- Method source: `{data['source_file']}` (`{data['source_sha256']}`)",
            f"- Product manifest: `{data['product_manifest']}` (`{data['product_manifest_sha256']}`)",
            "",
        ]
    )
    return "\n".join(lines)


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", dir=path.parent, delete=False, encoding="utf-8"
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def generate() -> dict[str, Any]:
    data = load_and_validate()
    write_atomic(JSON_OUTPUT, json.dumps(data, indent=2, sort_keys=True) + "\n")
    write_atomic(MARKDOWN_OUTPUT, render_markdown(data))
    return data


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    data = load_and_validate()
    expected_json = json.dumps(data, indent=2, sort_keys=True) + "\n"
    expected_markdown = render_markdown(data)
    if args.check:
        current = (
            JSON_OUTPUT.is_file()
            and JSON_OUTPUT.read_text(encoding="utf-8") == expected_json
            and MARKDOWN_OUTPUT.is_file()
            and MARKDOWN_OUTPUT.read_text(encoding="utf-8") == expected_markdown
        )
        if not current:
            print("stale: LM3 manufacturing-method package")
            return 1
        print("current: LM3 manufacturing-method package")
        return 0
    write_atomic(JSON_OUTPUT, expected_json)
    write_atomic(MARKDOWN_OUTPUT, expected_markdown)
    print(f"wrote {JSON_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"wrote {MARKDOWN_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
