"""Generate and validate the LM3 catalogue-candidate sourcing register."""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
import tomllib
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[4]
SOURCE = REPO_ROOT / "lib/templates/trainset-cots-candidates.toml"
MANIFEST = (
    REPO_ROOT
    / "design/component-catalogue/catalog/buildable-trainset"
    / "buildable-trainset-manifest.json"
)
OUTPUT_ROOT = REPO_ROOT / "design/component-catalogue/catalog/buildable-trainset"
JSON_OUTPUT = OUTPUT_ROOT / "cots-candidates.json"
MARKDOWN_OUTPUT = OUTPUT_ROOT / "cots-candidates.md"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_and_validate() -> dict[str, Any]:
    source = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    products = {item["id"]: item for item in manifest["product_items"]}
    external_ids = {
        item_id
        for item_id, item in products.items()
        if item["layer"] == "external-component"
    }
    candidates: dict[str, dict[str, Any]] = {}
    product_to_candidates: dict[str, list[str]] = {}
    for candidate in source["candidate"]:
        candidate_id = str(candidate["id"])
        if candidate_id in candidates:
            raise ValueError(f"duplicate COTS candidate {candidate_id}")
        candidates[candidate_id] = candidate
        for required in (
            "manufacturer",
            "model",
            "manufacturer_url",
            "source_class",
            "selection_state",
            "public_spec",
            "fit_required",
            "localisation",
        ):
            if not candidate.get(required):
                raise ValueError(f"{candidate_id} is missing {required}")
        if not str(candidate["manufacturer_url"]).startswith("https://"):
            raise ValueError(f"{candidate_id} must use a primary HTTPS source")
        for product_id in candidate["product_ids"]:
            if product_id not in external_ids:
                raise ValueError(
                    f"{candidate_id} references non-external or unknown {product_id}"
                )
            product_to_candidates.setdefault(str(product_id), []).append(candidate_id)

    uncovered = sorted(external_ids - set(product_to_candidates))
    if uncovered:
        raise ValueError(f"external product rows have no COTS/RFQ candidate: {uncovered}")
    exact_classes = {
        "exact-catalogue-product",
        "exact-catalogue-model",
        "exact-catalogue-part",
        "exact-catalogue-order",
    }
    exact_ids = {
        product_id
        for product_id, candidate_ids in product_to_candidates.items()
        if any(candidates[candidate_id]["source_class"] in exact_classes for candidate_id in candidate_ids)
    }
    return {
        **source,
        "source_file": str(SOURCE.relative_to(REPO_ROOT)),
        "source_sha256": _sha256(SOURCE),
        "product_manifest": str(MANIFEST.relative_to(REPO_ROOT)),
        "product_manifest_sha256": _sha256(MANIFEST),
        "coverage": {
            "external_product_rows": len(external_ids),
            "covered_external_product_rows": len(product_to_candidates),
            "rows_with_exact_catalogue_component": len(exact_ids),
            "candidate_count": len(candidates),
            "uncovered_product_ids": [],
        },
        "product_to_candidates": {
            key: sorted(value) for key, value in sorted(product_to_candidates.items())
        },
        "product_titles": {
            item_id: products[item_id]["title"] for item_id in sorted(external_ids)
        },
    }


def render_markdown(data: dict[str, Any]) -> str:
    coverage = data["coverage"]
    lines = [
        "# LM3 off-the-shelf and RFQ candidate register",
        "",
        "<!-- Generated by tools/automation/buildable-trainset.sh; do not hand-edit. -->",
        "",
        data["purpose"],
        "",
        f"**Release boundary:** {data['release_boundary']}",
        "",
        f"Manufacturer sources checked on **{data['checked_on']}**.",
        "",
        "A complete system such as a door, bogie, HVAC unit or gangway is vehicle-specific even when its supplier uses a standard platform. Exact catalogue components are therefore separated from RFQ baselines and partial interface kits.",
        "",
        "## Coverage",
        "",
        "| Measure | Value |",
        "|---|---:|",
        f"| Bought-in LM3 rows with a sourcing candidate | {coverage['covered_external_product_rows']} / {coverage['external_product_rows']} |",
        f"| Rows containing at least one exact catalogue component | {coverage['rows_with_exact_catalogue_component']} |",
        f"| Controlled candidates | {coverage['candidate_count']} |",
        "",
        "## Candidate components and systems",
        "",
        "| Candidate | Model and primary source | State | LM3 rows | Publicly established boundary |",
        "|---|---|---|---|---|",
    ]
    for row in data["candidate"]:
        product_ids = ", ".join(f"`{item}`" for item in row["product_ids"])
        public_spec = "; ".join(row["public_spec"])
        lines.append(
            f"| `{row['id']}` | [{row['manufacturer']} — {row['model']}]({row['manufacturer_url']}) | "
            f"{row['selection_state']} | {product_ids} | {public_spec} |"
        )
    lines.extend(["", "## Integration and closure actions", ""])
    for row in data["candidate"]:
        lines.extend(
            [
                f"### `{row['id']}` — {row['manufacturer']} {row['model']}",
                "",
                f"- Source class: `{row['source_class']}`",
                f"- Local manufacture: {row['localisation']}",
                "- Before freeze:",
            ]
        )
        lines.extend(f"  - {item}" for item in row["fit_required"])
        lines.append("")
    lines.extend(
        [
            "## Controlled inputs",
            "",
            f"- Candidate source: `{data['source_file']}` (`{data['source_sha256']}`)",
            f"- Product manifest: `{data['product_manifest']}` (`{data['product_manifest_sha256']}`)",
            "",
        ]
    )
    return "\n".join(lines)


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", dir=path.parent, delete=False, encoding="utf-8"
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def generate() -> dict[str, Any]:
    data = load_and_validate()
    _write_atomic(JSON_OUTPUT, json.dumps(data, indent=2, sort_keys=True) + "\n")
    _write_atomic(MARKDOWN_OUTPUT, render_markdown(data))
    return data


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    data = load_and_validate()
    expected_json = json.dumps(data, indent=2, sort_keys=True) + "\n"
    expected_md = render_markdown(data)
    if args.check:
        if not JSON_OUTPUT.exists() or JSON_OUTPUT.read_text(encoding="utf-8") != expected_json:
            raise SystemExit(f"stale generated file: {JSON_OUTPUT}")
        if not MARKDOWN_OUTPUT.exists() or MARKDOWN_OUTPUT.read_text(encoding="utf-8") != expected_md:
            raise SystemExit(f"stale generated file: {MARKDOWN_OUTPUT}")
    else:
        generate()
    coverage = data["coverage"]
    print(
        f"COTS candidates: {coverage['candidate_count']}; covered bought-in rows: "
        f"{coverage['covered_external_product_rows']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
