"""Generate and validate the LM3 supplier-anchor and local-equivalence register."""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
import tomllib
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[4]
SOURCE = REPO_ROOT / "lib/templates/trainset-supplier-anchors.toml"
MANIFEST = (
    REPO_ROOT
    / "design/component-catalogue/catalog/buildable-trainset"
    / "buildable-trainset-manifest.json"
)
OUTPUT_ROOT = REPO_ROOT / "design/component-catalogue/catalog/buildable-trainset"
JSON_OUTPUT = OUTPUT_ROOT / "supplier-anchors.json"
MARKDOWN_OUTPUT = OUTPUT_ROOT / "supplier-anchors.md"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_and_validate() -> dict[str, Any]:
    source = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    products = {item["id"]: item for item in manifest["product_items"]}
    external_ids = {
        item_id
        for item_id, item in products.items()
        if item["layer"] == "external-component"
    }
    anchors: dict[str, dict[str, Any]] = {}
    product_to_anchor: dict[str, str] = {}
    for anchor in source["anchor"]:
        anchor_id = str(anchor["id"])
        if anchor_id in anchors:
            raise ValueError(f"duplicate supplier anchor {anchor_id}")
        anchors[anchor_id] = anchor
        url = str(anchor["manufacturer_url"])
        if not url.startswith("https://"):
            raise ValueError(f"{anchor_id} must use a primary HTTPS manufacturer URL")
        for required in (
            "manufacturer",
            "product_family",
            "anchor_type",
            "procurement_state",
            "localisation",
            "fit_gaps",
        ):
            if not anchor.get(required):
                raise ValueError(f"{anchor_id} is missing {required}")
        for product_id in anchor["product_ids"]:
            if product_id not in external_ids:
                raise ValueError(f"{anchor_id} references non-external or unknown {product_id}")
            if product_id in product_to_anchor:
                raise ValueError(
                    f"{product_id} is covered by both {product_to_anchor[product_id]} and {anchor_id}"
                )
            product_to_anchor[str(product_id)] = anchor_id

    uncovered = sorted(external_ids - set(product_to_anchor))
    if uncovered:
        raise ValueError(f"external product rows have no supplier anchor: {uncovered}")

    assemblies = {item["id"]: item for item in manifest["assemblies"]}
    return {
        **source,
        "source_file": str(SOURCE.relative_to(REPO_ROOT)),
        "source_sha256": _sha256(SOURCE),
        "product_manifest": str(MANIFEST.relative_to(REPO_ROOT)),
        "product_manifest_sha256": _sha256(MANIFEST),
        "coverage": {
            "external_product_rows": len(external_ids),
            "covered_external_product_rows": len(product_to_anchor),
            "anchor_count": len(anchors),
            "uncovered_product_ids": [],
        },
        "product_to_anchor": dict(sorted(product_to_anchor.items())),
        "product_titles": {item_id: products[item_id]["title"] for item_id in sorted(products)},
        "assembly_titles": {item_id: assemblies[item_id]["title"] for item_id in sorted(assemblies)},
    }


def _parent_map(manifest: dict[str, Any]) -> dict[str, list[str]]:
    parents: dict[str, list[str]] = {}
    for assembly in manifest["assemblies"]:
        for child in assembly["children"]:
            parents.setdefault(child, []).append(assembly["id"])
    return {key: sorted(value) for key, value in parents.items()}


def _paths_to_trainset(item_id: str, parents: dict[str, list[str]]) -> list[list[str]]:
    if item_id == "LM3-TRAINSET-A000":
        return [[item_id]]
    paths: list[list[str]] = []
    for parent in parents.get(item_id, []):
        for path in _paths_to_trainset(parent, parents):
            paths.append([item_id, *path])
    return paths


def render_markdown(data: dict[str, Any]) -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    products = {item["id"]: item for item in manifest["product_items"]}
    assemblies = {item["id"]: item for item in manifest["assemblies"]}
    titles = {**{key: value["title"] for key, value in products.items()}, **{key: value["title"] for key, value in assemblies.items()}}
    coverage = data["coverage"]
    lines = [
        "# LM3 supplier anchors and local equivalents",
        "",
        "<!-- Generated by tools/automation/buildable-trainset.sh; do not hand-edit. -->",
        "",
        data["purpose"],
        "",
        f"**Release boundary:** {data['release_boundary']}",
        "",
        f"Checked against manufacturer sources on **{data['checked_on']}**.",
        "",
        "## How to use this register",
        "",
        "1. Use the named family to obtain an RFQ, sample, interface drawing and evidence pack; do not infer an order code from the family page.",
        "2. Freeze the chosen order code/configuration and its controlled supplier documents in the city revision.",
        "3. A local supplier may propose an equivalent. Compare it against every mandatory rule and product acceptance item, then repeat affected subassembly and vehicle tests.",
        "4. Preserve the original anchor, accepted-equivalent record and hashes so later regeneration changes cost and geometry without silently changing safety assumptions.",
        "",
        "Mandatory equivalence dossier:",
        "",
    ]
    lines.extend(f"- {rule}" for rule in data["equivalence"]["required"])
    lines.extend(
        [
            "",
            "## Controlled coverage",
            "",
            "| Measure | Value |",
            "|---|---:|",
            f"| Bought-in product rows with one primary anchor | {coverage['covered_external_product_rows']} / {coverage['external_product_rows']} |",
            f"| Primary anchor families | {coverage['anchor_count']} |",
            "",
            "## Anchor families",
            "",
            "| Anchor | Manufacturer product family | State | Product rows | Local-equivalent route |",
            "|---|---|---|---|---|",
        ]
    )
    for anchor in data["anchor"]:
        product_links = ", ".join(f"`{item_id}`" for item_id in anchor["product_ids"])
        lines.append(
            f"| `{anchor['id']}` | [{anchor['manufacturer']} — {anchor['product_family']}]({anchor['manufacturer_url']}) | "
            f"{anchor['procurement_state']} | {product_links} | {anchor['localisation']} |"
        )

    parents = _parent_map(manifest)
    critical = [
        "LM3-BDY-P010",
        "LM3-BDY-P020",
        "LM3-BDY-P030",
        "LM3-CWL-P010",
        "LM3-END-P010",
        "LM3-ART-P020",
        "LM3-ART-P022",
        "LM3-ART-P024",
        "LM3-BOG-P040",
        "LM3-BOG-P042",
        "LM3-BOG-P046",
        "LM3-BOG-P048",
        "LM3-TRC-P010",
        "LM3-TRC-P020",
    ]
    lines.extend(
        [
            "",
            "## Parts → subassemblies → final trainset",
            "",
            "These generated chains make the structural and mechanical ownership explicit. Repeated car/end/joint quantities remain in the product manifest.",
            "",
            "| Starting part | Controlled assembly chain |",
            "|---|---|",
        ]
    )
    for item_id in critical:
        paths = _paths_to_trainset(item_id, parents)
        chain = min(paths, key=len) if paths else [item_id]
        chain_text = " → ".join(f"`{node}` {titles.get(node, '')}" for node in chain)
        lines.append(f"| `{item_id}` {titles[item_id]} | {chain_text} |")

    lines.extend(
        [
            "",
            "## Known fit gaps",
            "",
        ]
    )
    for anchor in data["anchor"]:
        lines.append(f"- `{anchor['id']}`: {'; '.join(anchor['fit_gaps'])}")
    lines.extend(
        [
            "",
            "## Controlled inputs",
            "",
            f"- Anchor source: `{data['source_file']}` (`{data['source_sha256']}`)",
            f"- Product manifest: `{data['product_manifest']}` (`{data['product_manifest_sha256']}`)",
            "",
        ]
    )
    return "\n".join(lines)


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False, encoding="utf-8") as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def generate() -> dict[str, Any]:
    data = load_and_validate()
    _write_atomic(JSON_OUTPUT, json.dumps(data, indent=2, sort_keys=True) + "\n")
    _write_atomic(MARKDOWN_OUTPUT, render_markdown(data))
    return data


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    data = load_and_validate()
    expected_json = json.dumps(data, indent=2, sort_keys=True) + "\n"
    expected_md = render_markdown(data)
    if args.check:
        if not JSON_OUTPUT.exists() or JSON_OUTPUT.read_text(encoding="utf-8") != expected_json:
            raise SystemExit(f"stale generated file: {JSON_OUTPUT}")
        if not MARKDOWN_OUTPUT.exists() or MARKDOWN_OUTPUT.read_text(encoding="utf-8") != expected_md:
            raise SystemExit(f"stale generated file: {MARKDOWN_OUTPUT}")
    else:
        generate()
    print(
        f"supplier anchors: {data['coverage']['anchor_count']}; "
        f"covered bought-in rows: {data['coverage']['covered_external_product_rows']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
