#!/usr/bin/env python3
"""Generate a central index of Markdown documentation files."""

from __future__ import annotations

import subprocess
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = REPO_ROOT / "docs" / "INDEX.md"
SKIP_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "node_modules",
    "target",
}


def _git_markdown_files() -> list[Path]:
    tracked = subprocess.check_output(
        ["git", "ls-files", "*.md"],
        cwd=REPO_ROOT,
        text=True,
    ).splitlines()
    untracked = subprocess.check_output(
        ["git", "ls-files", "--others", "--exclude-standard", "*.md"],
        cwd=REPO_ROOT,
        text=True,
    ).splitlines()
    paths = sorted({Path(p) for p in tracked + untracked})
    return [
        p
        for p in paths
        if not SKIP_PARTS.intersection(p.parts) and (REPO_ROOT / p).exists()
    ]


def _title(path: Path) -> str:
    try:
        for line in (REPO_ROOT / path).read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except UnicodeDecodeError:
        pass
    if path.name == "README.md":
        return path.parent.name or "Repository README"
    return path.stem.replace("-", " ").replace("_", " ").title()


def _section(path: Path) -> str:
    if len(path.parts) == 1:
        return "Repository Root"
    return path.parts[0]


def _link(path: Path) -> str:
    return Path("..", path).as_posix()


def generate() -> str:
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in _git_markdown_files():
        grouped[_section(path)].append(path)

    lines = [
        "# Generated Markdown Inventory",
        "",
        "This file is generated by `tools/automation/generate-doc-index.py`.",
        "It is an exhaustive file inventory for search and CI diagnostics, not a",
        "reading path or source of truth. Use the root [`README.md`](../README.md)",
        "for approachable navigation and the authoritative source map.",
        "Local `README.md` files remain beside the code, designs, or generated",
        "artifacts they describe.",
        "",
        "Regenerate from the repository root with:",
        "",
        "```bash",
        "python3 tools/automation/generate-doc-index.py",
        "```",
        "",
    ]

    total = sum(len(paths) for paths in grouped.values())
    lines.extend(
        [
            f"Indexed Markdown files: **{total}**.",
            "",
            "## Sections",
            "",
            "| Section | Files |",
            "|---|---:|",
        ]
    )
    for section in sorted(grouped):
        anchor = section.lower().replace(" ", "-")
        lines.append(f"| [{section}](#{anchor}) | {len(grouped[section])} |")

    for section in sorted(grouped):
        lines.extend(["", f"## {section}", "", "| File | Title |", "|---|---|"])
        for path in grouped[section]:
            lines.append(f"| [`{path.as_posix()}`]({_link(path)}) | {_title(path)} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(generate(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
