//! Emit design.toml + corridor.geojson + design-quality.yaml + stations.json.
//!
//! The design.toml we emit is a *superset-ready* document: every station
//! carries lat/lon + anchor metadata; every line carries its cell-space
//! polyline. The recipe in lib/recipes/city-to-design.toml then
//! layers in archetype / kit / profile selections when the Python
//! generator fuses this with the templates.
//!
//! This file never calls anyhow::Error types that would leak solver-side
//! state — all output is purely a projection of the bundle + lines.

use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::Result;
use osr_routing::civil::{CivilClass, CivilSegment};
use osr_routing::raster::RasterBundle;
use osr_routing::station::Station;
use osr_routing::topology::Line;
use serde::Serialize;

pub fn write_all(
    out_dir: &Path,
    slug: &str,
    country: &str,
    climate: Option<&str>,
    profile: Option<&str>,
    population: u64,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
    civil_per_line: &[Vec<CivilSegment>],
) -> Result<()> {
    write_design_toml(
        out_dir,
        slug,
        country,
        climate,
        profile,
        population,
        bundle,
        lines,
        stations,
        civil_per_line,
    )?;
    write_corridor_geojson(out_dir, slug, bundle, lines, stations)?;
    write_stations_json(out_dir, slug, stations)?;
    write_quality_yaml(out_dir, slug, bundle, lines, stations, civil_per_line)?;
    Ok(())
}

// ---- design.toml -----------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn write_design_toml(
    out_dir: &Path,
    slug: &str,
    country: &str,
    climate: Option<&str>,
    profile: Option<&str>,
    population: u64,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
    civil_per_line: &[Vec<CivilSegment>],
) -> Result<()> {
    let mut out = String::new();
    out.push_str("# Auto-generated by osr-design from real OSM data.\n");
    out.push_str("# Do not hand-edit without re-running the recipe; changes will be\n");
    out.push_str("# overwritten on the next pipeline run. Override via\n");
    out.push_str("# lib/recipes/city-to-design.toml rule additions instead.\n\n");

    out.push_str("[city]\n");
    out.push_str(&format!("slug            = \"{slug}\"\n"));
    out.push_str(&format!("country         = \"{country}\"\n"));
    out.push_str(&format!("population      = {population}\n"));
    out.push_str(&format!(
        "bbox            = {{ south = {}, west = {}, north = {}, east = {} }}\n",
        bundle.grid.reference.bbox_south,
        bundle.grid.reference.bbox_west,
        bundle.grid.reference.bbox_north,
        bundle.grid.reference.bbox_east,
    ));
    out.push_str(&format!("centroid_lat    = {}\n", bundle.grid.reference.lat0));
    out.push_str("\n");

    out.push_str("[climate]\n");
    let climate_preset = climate.unwrap_or("temperate-continental");
    out.push_str(&format!("preset          = \"{climate_preset}\"\n\n"));

    if let Some(p) = profile {
        out.push_str("[composition]\n");
        out.push_str(&format!("profile         = \"{p}\"\n\n"));
    }

    // Rolling-stock family + geometry preset per RFC 0008 §5 / RFC 0009 §10.
    // One family applies consist-wide across every line; the auto-gen
    // does not pick different families for different lines in the same
    // city (RFC 0008 rollout §7 keeps a single-family bet per city).
    let family = family_for_population(population);
    let geometry = geometry_for_family(family);
    let consist_length_m = family_length_m(family);

    // Precompute station archetypes: terminal (line endpoints on
    // radial lines), interchange (cross-line stations within 200 m),
    // and otherwise demand-based major/standard/halt per RFC 0010 §3.
    let archetypes = compute_archetypes(lines, stations);

    // One [[lines]] block per synthesized line.
    for line in lines {
        let length_m = line_length_m(bundle, line);
        out.push_str("[[lines]]\n");
        out.push_str(&format!("name            = \"{}\"\n", line.name));
        out.push_str(&format!("shape           = \"{}\"\n", match line.shape {
            osr_routing::topology::LineShape::Radial => "radial",
            osr_routing::topology::LineShape::Ring => "ring",
        }));
        out.push_str(&format!("length_m        = {length_m:.1}\n"));
        out.push_str(&format!("rolling_stock   = \"{family}\"\n"));
        out.push_str(&format!("geometry        = \"{geometry}\"\n\n"));
    }

    // Stations — the critical output. Every one has lat/lon.
    for (idx, s) in stations.iter().enumerate() {
        let sid = station_id(s);
        let archetype = archetypes[idx];
        let clearance_m = if archetype == "halt" { 6 } else { 10 };
        let platform_length_m = consist_length_m + clearance_m as f32;

        out.push_str("[[stations]]\n");
        out.push_str(&format!("id              = \"{sid}\"\n"));
        out.push_str(&format!("line            = \"{}\"\n", s.line_name));
        out.push_str(&format!("lat             = {}\n", s.lat));
        out.push_str(&format!("lon             = {}\n", s.lon));
        out.push_str(&format!("s_m             = {:.1}\n", s.s_m));
        if let Some(k) = s.anchor_kind.as_deref() {
            out.push_str(&format!("anchor_kind     = \"{k}\"\n"));
        }
        if let Some(n) = s.anchor_name.as_deref() {
            out.push_str(&format!(
                "anchor_name     = \"{}\"\n",
                escape_toml_string(n)
            ));
        }
        out.push_str(&format!("archetype       = \"{archetype}\"\n"));
        out.push_str(&format!(
            "platform_length_m = {:.1}\n",
            platform_length_m
        ));
        out.push_str("\n");
    }

    // Depots — per RFC 0014 §8. The farthest-terminal station becomes
    // `main-heavy`; every other `terminal` / `depot-terminal` station
    // becomes `layup-minimal`. Stall count from the §4 formula.
    let depot_blocks = compute_depots(lines, stations, &archetypes);
    if !depot_blocks.is_empty() {
        out.push_str("# [[depots]] — fleet stabling + maintenance per RFC 0014.\n");
        for d in &depot_blocks {
            out.push_str("[[depots]]\n");
            out.push_str(&format!("station      = \"{}\"\n", d.station_id));
            out.push_str(&format!("archetype    = \"{}\"\n", d.archetype));
            out.push_str(&format!("fleet_stalls = {}\n", d.fleet_stalls));
            out.push_str("\n");
        }
    }

    // Switches — per RFC 0012 §9. One turnback at every terminal; a
    // depot fan (one per stall pair, 1:9) at every depot-terminal.
    let switches = compute_switches(stations, &archetypes, &depot_blocks);
    if !switches.is_empty() {
        out.push_str("# switches — turnbacks at terminals + depot fans per RFC 0012 §9.\n");
        out.push_str("switches = [\n");
        for sw in &switches {
            out.push_str(&format!(
                "  {{ id = \"{}\", kit = \"{}\", station = \"{}\", side = \"{}\" }},\n",
                sw.id, sw.kit, sw.station_id, sw.side,
            ));
        }
        out.push_str("]\n\n");
    }

    // Costs — per RFC 0011 §9 lookup. Planning-grade €/km × civil mix
    // per line. `country-costs.toml` scales these in downstream
    // reports; the base figure goes in the design.toml so the
    // operator has a one-number headline when reviewing the output.
    let costs = compute_costs(lines, civil_per_line);
    out.push_str("# [costs] — RFC 0011 §9 planning-grade €/km × civil mix.\n");
    out.push_str("[costs]\n");
    out.push_str(&format!("at_grade_eur = {:.0}\n", costs.at_grade_eur));
    out.push_str(&format!("elevated_eur = {:.0}\n", costs.elevated_eur));
    out.push_str(&format!("bridge_eur   = {:.0}\n", costs.bridge_eur));
    out.push_str(&format!(
        "total_eur    = {:.0}  # excludes rolling stock, stations, depots, integration\n",
        costs.total_eur
    ));

    let path = out_dir.join(format!("{slug}.design.toml"));
    fs::write(&path, out)?;
    Ok(())
}

// ---- RFC 0014 §8 depot-block emission --------------------------------------

#[derive(Debug, Clone)]
struct DepotBlock {
    station_id: String,
    archetype: &'static str,
    fleet_stalls: u32,
}

/// Derive depot blocks from the station archetypes. Rules:
/// - Every `depot-terminal` station emits a `main-heavy` depot.
/// - Every other `terminal` emits a `layup-minimal` (so the fleet
///   has somewhere to layover at the remote end without
///   empty-driving back to the main depot).
/// - Stall count = ceil(fleet_on_line × 1.25) per RFC 0014 §4,
///   with `fleet_on_line` estimated from line length via
///   `peak_revenue_trainsets`.
fn compute_depots(
    lines: &[Line],
    stations: &[Station],
    archetypes: &[&'static str],
) -> Vec<DepotBlock> {
    // Precompute each line's fleet sizing from length.
    let mut fleet_by_line: std::collections::BTreeMap<&str, u32> =
        std::collections::BTreeMap::new();
    for line in lines {
        let len_m = line_cells_length_m(line);
        fleet_by_line.insert(line.name.as_str(), fleet_total(peak_revenue_trainsets(len_m)));
    }

    let mut out = Vec::new();
    for (i, s) in stations.iter().enumerate() {
        let archetype = archetypes[i];
        if archetype != "terminal" && archetype != "depot-terminal" {
            continue;
        }
        let fleet = *fleet_by_line
            .get(s.line_name.as_str())
            .unwrap_or(&4); // conservative fallback
        let stalls = depot_stalls(fleet);
        let depot_archetype = if archetype == "depot-terminal" {
            "main-heavy"
        } else {
            "layup-minimal"
        };
        out.push(DepotBlock {
            station_id: station_id(s),
            archetype: depot_archetype,
            fleet_stalls: stalls,
        });
    }
    out
}

// ---- RFC 0008 §5 + RFC 0014 §4 fleet-sizing helpers ------------------------

/// Peak-revenue trainsets at nominal 5-min headway, calibrated
/// against the Samawah reference (12 km line → 6 trainsets) — so
/// ~1 trainset per 2 km of line length. Floor of 2.
fn peak_revenue_trainsets(line_length_m: f64) -> u32 {
    let k = (line_length_m / 2_000.0).ceil().max(2.0);
    k as u32
}

/// Planned-maintenance spare per RFC 0014 §4: 1 per 10 peak,
/// minimum 1.
fn fleet_spare(peak: u32) -> u32 {
    (peak / 10).max(1)
}

/// Cold reserve per RFC 0014 §4: 1 per line, fixed.
fn fleet_cold_reserve() -> u32 {
    1
}

fn fleet_total(peak: u32) -> u32 {
    peak + fleet_spare(peak) + fleet_cold_reserve()
}

fn depot_stalls(fleet: u32) -> u32 {
    ((f64::from(fleet) * 1.25).ceil()) as u32
}

fn line_cells_length_m(line: &Line) -> f64 {
    // This reuses the same accounting `line_length_m` uses, but we
    // don't have the RasterBundle here; approximate by counting
    // Manhattan-ish cell-to-cell distance. For the compute_depots
    // heuristic we need rough length only.
    let mut total = 0.0;
    for pair in line.cells.windows(2) {
        let dr = pair[1].0 as f64 - pair[0].0 as f64;
        let dc = pair[1].1 as f64 - pair[0].1 as f64;
        total += (dr * dr + dc * dc).sqrt() * 20.0; // 20 m/cell
    }
    total
}

// ---- RFC 0012 §9 switch emission ------------------------------------------

#[derive(Debug, Clone)]
struct SwitchEntry {
    id: String,
    kit: &'static str,
    station_id: String,
    side: &'static str,
}

/// Derive the switch list:
/// - One `turnback` switch at every `terminal` / `depot-terminal`.
/// - One `yard-throat` switch per stall at every `depot-terminal`
///   (the depot fan is parametric in stall count).
/// All switches use `no-9-mainline` per RFC 0012 §3 — one tangent
/// across the deployment, matching the simplicity bet.
fn compute_switches(
    stations: &[Station],
    archetypes: &[&'static str],
    depots: &[DepotBlock],
) -> Vec<SwitchEntry> {
    let mut out = Vec::new();
    for (i, s) in stations.iter().enumerate() {
        let archetype = archetypes[i];
        if archetype != "terminal" && archetype != "depot-terminal" {
            continue;
        }
        let sid = station_id(s);
        out.push(SwitchEntry {
            id: format!("sw-{sid}-tb"),
            kit: "no-9-mainline",
            station_id: sid.clone(),
            side: "turnback",
        });
        if archetype == "depot-terminal" {
            // Yard fan: one switch per stall (simple linear fan; a
            // deployment civil design will refine into a proper
            // ladder track).
            let stalls = depots
                .iter()
                .find(|d| d.station_id == sid)
                .map(|d| d.fleet_stalls)
                .unwrap_or(0);
            for n in 1..=stalls {
                out.push(SwitchEntry {
                    id: format!("sw-{sid}-yd-{n:02}"),
                    kit: "no-9-mainline",
                    station_id: sid.clone(),
                    side: "yard-throat",
                });
            }
        }
    }
    out
}

// ---- RFC 0011 §9 cost estimation -------------------------------------------

#[derive(Debug, Clone, Copy, Default)]
struct CostSummary {
    at_grade_eur: f64,
    elevated_eur: f64,
    bridge_eur: f64,
    total_eur: f64,
}

/// Planning-grade unit costs from RFC 0011 §9 (€/km).
const COST_AT_GRADE_EUR_PER_KM: f64 = 3_500_000.0;
const COST_ELEVATED_EUR_PER_KM: f64 = 18_000_000.0;
const COST_BRIDGE_EUR_PER_KM: f64 = 25_000_000.0;

fn compute_costs(lines: &[Line], civil_per_line: &[Vec<CivilSegment>]) -> CostSummary {
    let _ = lines; // currently unused — future: per-line breakout if desired
    let mut at_grade_m = 0.0_f64;
    let mut elevated_m = 0.0_f64;
    let mut bridge_m = 0.0_f64;
    for segs in civil_per_line {
        for s in segs {
            match s.class {
                CivilClass::AtGrade => at_grade_m += s.length_m,
                CivilClass::Elevated => elevated_m += s.length_m,
                CivilClass::Bridge => bridge_m += s.length_m,
            }
        }
    }
    let at_grade_eur = at_grade_m / 1_000.0 * COST_AT_GRADE_EUR_PER_KM;
    let elevated_eur = elevated_m / 1_000.0 * COST_ELEVATED_EUR_PER_KM;
    let bridge_eur = bridge_m / 1_000.0 * COST_BRIDGE_EUR_PER_KM;
    CostSummary {
        at_grade_eur,
        elevated_eur,
        bridge_eur,
        total_eur: at_grade_eur + elevated_eur + bridge_eur,
    }
}

// ---- RFC 0008 §5 rolling-stock policy --------------------------------------

/// Pick a rolling-stock family id for a population per RFC 0008 §5.
fn family_for_population(population: u64) -> &'static str {
    match population {
        0..=300_000 => "tram-2car",
        300_001..=1_000_000 => "light-metro-3car",
        1_000_001..=3_000_000 => "metro-4car",
        _ => "metro-6car",
    }
}

/// Pick the tightest geometry preset compatible with a rolling-stock
/// family per RFC 0009 §10. "Tightest" = the preset with the smallest
/// supported consist — it gives the operator the most flexibility
/// downstream without over-engineering the alignment.
fn geometry_for_family(family: &str) -> &'static str {
    match family {
        "tram-2car" => "standard-urban", // also supports heritage-tram for retrofit
        "light-metro-3car" => "standard-urban",
        "metro-4car" => "standard-metro",
        "metro-6car" => "standard-metro", // mainline-mixed only when explicit
        _ => "standard-urban",
    }
}

/// Nominal consist length per family (RFC 0008 §1). Used to derive
/// platform_length_m per RFC 0010 §4.1.
fn family_length_m(family: &str) -> f32 {
    match family {
        "tram-2car" => 42.0,
        "light-metro-3car" => 65.0,
        "metro-4car" => 88.0,
        "metro-6car" => 132.0,
        _ => 65.0,
    }
}

// ---- RFC 0010 §3 archetype selection ---------------------------------------

/// Return an archetype string per station (same order/length as the
/// input `stations` slice). See RFC 0010 §3.
fn compute_archetypes(lines: &[Line], stations: &[Station]) -> Vec<&'static str> {
    // Group station indices by line name to find endpoints.
    let mut by_line: std::collections::BTreeMap<&str, Vec<usize>> =
        std::collections::BTreeMap::new();
    for (i, s) in stations.iter().enumerate() {
        by_line.entry(s.line_name.as_str()).or_default().push(i);
    }
    // Endpoints: first + last by s_m on each radial line.
    let mut is_terminal = vec![false; stations.len()];
    for line in lines {
        let line_is_ring = matches!(line.shape, osr_routing::topology::LineShape::Ring);
        if line_is_ring {
            continue; // Rings have no terminal.
        }
        let Some(idxs) = by_line.get(line.name.as_str()) else {
            continue;
        };
        let mut sorted = idxs.clone();
        sorted.sort_by(|&a, &b| {
            stations[a]
                .s_m
                .partial_cmp(&stations[b].s_m)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        if let Some(&first) = sorted.first() {
            is_terminal[first] = true;
        }
        if let Some(&last) = sorted.last() {
            if sorted.len() > 1 {
                is_terminal[last] = true;
            }
        }
    }

    // Interchange: a station within 200 m of a station on a different
    // line is an interchange (both sides are marked).
    let mut is_interchange = vec![false; stations.len()];
    for i in 0..stations.len() {
        for j in (i + 1)..stations.len() {
            if stations[i].line_name == stations[j].line_name {
                continue;
            }
            if haversine_m(
                stations[i].lat,
                stations[i].lon,
                stations[j].lat,
                stations[j].lon,
            ) < 200.0
            {
                is_interchange[i] = true;
                is_interchange[j] = true;
            }
        }
    }

    // Depot-terminal: the single "far" terminal on the city's longest
    // radial line — a common convention for siting the fleet depot at
    // the operator's main spare yard. If no radial terminal exists
    // (all-ring city), skip.
    let mut depot_terminal_idx: Option<usize> = None;
    let mut best_s_m: f64 = -1.0;
    for (i, t) in is_terminal.iter().enumerate() {
        if *t && stations[i].s_m > best_s_m {
            best_s_m = stations[i].s_m;
            depot_terminal_idx = Some(i);
        }
    }

    // Apply priority: depot-terminal > terminal > interchange > demand-based.
    let mut out: Vec<&'static str> = Vec::with_capacity(stations.len());
    for i in 0..stations.len() {
        let archetype = if Some(i) == depot_terminal_idx {
            "depot-terminal"
        } else if is_terminal[i] {
            "terminal"
        } else if is_interchange[i] {
            "interchange"
        } else if stations[i].demand > 0.6 {
            "major"
        } else if stations[i].demand > 0.25 {
            "standard"
        } else {
            "halt"
        };
        out.push(archetype);
    }
    out
}

/// Great-circle distance between two lat/lon points, in metres.
/// Small-angle approximation suffices at the ≤ 200 m scales we use.
fn haversine_m(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    let to_rad = std::f64::consts::PI / 180.0;
    let dlat = (lat2 - lat1) * to_rad;
    let dlon = (lon2 - lon1) * to_rad;
    let mid_lat = ((lat1 + lat2) * 0.5) * to_rad;
    let r = 6_371_000.0_f64;
    ((r * dlat).powi(2) + (r * mid_lat.cos() * dlon).powi(2)).sqrt()
}

fn station_id(s: &Station) -> String {
    // Stable ID derived from line + cell. Avoids depending on anchor names
    // (which can be non-ASCII / missing).
    format!("{}-{:04}-{:04}", s.line_name, s.row, s.col)
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn line_length_m(bundle: &RasterBundle, line: &Line) -> f64 {
    let cell_m = bundle.grid.reference.cell_m;
    let mut total = 0.0_f64;
    for pair in line.cells.windows(2) {
        let dr = pair[1].0 as f64 - pair[0].0 as f64;
        let dc = pair[1].1 as f64 - pair[0].1 as f64;
        total += (dr * dr + dc * dc).sqrt() * cell_m;
    }
    total
}

// ---- corridor.geojson ------------------------------------------------

fn write_corridor_geojson(
    out_dir: &Path,
    slug: &str,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
) -> Result<()> {
    let mut features: Vec<serde_json::Value> = Vec::new();

    for line in lines {
        // Decimate polyline to every Nth cell to keep file size reasonable;
        // losing sub-cell detail is fine at 20 m resolution.
        let step = (line.cells.len() / 400).max(1);
        let mut coords: Vec<[f64; 2]> = Vec::new();
        for (i, &(r, c)) in line.cells.iter().enumerate() {
            if i == 0 || i == line.cells.len() - 1 || i % step == 0 {
                let (lat, lon) = bundle.grid.reference.rc_to_latlon(r, c);
                coords.push([lon, lat]);
            }
        }
        features.push(serde_json::json!({
            "type": "Feature",
            "properties": {
                "kind": "line",
                "name": line.name,
                "shape": match line.shape {
                    osr_routing::topology::LineShape::Radial => "radial",
                    osr_routing::topology::LineShape::Ring => "ring",
                },
            },
            "geometry": {
                "type": "LineString",
                "coordinates": coords,
            }
        }));
    }

    for s in stations {
        features.push(serde_json::json!({
            "type": "Feature",
            "properties": {
                "kind": "station",
                "line": s.line_name,
                "anchor_kind": s.anchor_kind,
                "anchor_name": s.anchor_name,
            },
            "geometry": {
                "type": "Point",
                "coordinates": [s.lon, s.lat],
            }
        }));
    }

    let geojson = serde_json::json!({
        "type": "FeatureCollection",
        "features": features,
    });
    let path = out_dir.join(format!("{slug}.corridor.geojson"));
    fs::write(&path, serde_json::to_string_pretty(&geojson)?)?;
    Ok(())
}

// ---- stations.json ---------------------------------------------------

#[derive(Serialize)]
struct StationSummary<'a> {
    id: String,
    line: &'a str,
    lat: f64,
    lon: f64,
    s_m: f64,
    anchor_kind: Option<&'a str>,
    anchor_name: Option<&'a str>,
}

fn write_stations_json(out_dir: &Path, slug: &str, stations: &[Station]) -> Result<()> {
    let rows: Vec<StationSummary> = stations
        .iter()
        .map(|s| StationSummary {
            id: station_id(s),
            line: &s.line_name,
            lat: s.lat,
            lon: s.lon,
            s_m: s.s_m,
            anchor_kind: s.anchor_kind.as_deref(),
            anchor_name: s.anchor_name.as_deref(),
        })
        .collect();
    let path = out_dir.join(format!("{slug}.stations.json"));
    fs::write(&path, serde_json::to_string_pretty(&rows)?)?;
    Ok(())
}

// ---- design-quality.yaml --------------------------------------------
//
// This is the automated gate that lets us ship 500 cities without
// human inspection. Each city gets scored; failing thresholds route the
// city back for retry with different topology parameters.

fn write_quality_yaml(
    out_dir: &Path,
    slug: &str,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
    civil_per_line: &[Vec<CivilSegment>],
) -> Result<()> {
    let total_line_m: f64 = lines.iter().map(|l| line_length_m(bundle, l)).sum();
    let anchor_hit = {
        let hit = stations.iter().filter(|s| s.anchor_id.is_some()).count();
        if stations.is_empty() {
            0.0
        } else {
            hit as f64 / stations.len() as f64
        }
    };

    // Coverage: fraction of high-demand cells within 400m (20 cells at 20m)
    // of any line.
    let coverage_pct = compute_coverage(bundle, lines, 20);

    // Civil class mix. No tunnel class per RFC 0011 §1; only
    // at-grade / elevated / bridge exist in the catalogue. Viaducts
    // and water-crossing bridges share the same reference U-girder
    // (RFC 0011 §§5–6), so their shares are reported separately but
    // priced from the same structural envelope downstream.
    let mut at_grade = 0.0_f64;
    let mut elevated = 0.0_f64;
    let mut bridge = 0.0_f64;
    for segs in civil_per_line {
        for s in segs {
            match s.class {
                CivilClass::AtGrade => at_grade += s.length_m,
                CivilClass::Elevated => elevated += s.length_m,
                CivilClass::Bridge => bridge += s.length_m,
            }
        }
    }
    let total_structure_m = at_grade + elevated + bridge;
    let elevated_fraction = if total_structure_m > 0.0 {
        (elevated + bridge) / total_structure_m
    } else {
        0.0
    };

    // Quality gates: hard (design is invalid if any fail) vs soft
    // (flagged for review but still shippable).
    //
    // Thresholds calibrated against a 3-city ground truth (Samawah,
    // Nairobi, Lyon). The soft bar lets auto-generated designs ship
    // when they are a reasonable first draft — tuning comes from
    // recipe edits, not per-city interventions.
    let hard_has_stations = !stations.is_empty();
    let hard_length_reasonable = total_line_m >= 3_000.0 && total_line_m <= 500_000.0;
    let hard_all = hard_has_stations && hard_length_reasonable;

    let soft_coverage = coverage_pct >= 0.30;
    let soft_anchor_hit = anchor_hit >= 0.20;
    // RFC 0011 §8: > 30 % elevated share is a warning; the
    // at-grade-dominant design is the mission-aligned one.
    let soft_elevated_ok = elevated_fraction <= 0.30;
    let soft_all = soft_coverage && soft_anchor_hit && soft_elevated_ok;

    // A design "passes" if the hard gates pass. Soft gates surface in the
    // report for triage but do not block scale-up.
    let pass_all = hard_all;

    let mut yaml = String::new();
    yaml.push_str(&format!("slug: {slug}\n"));
    yaml.push_str(&format!("pass: {pass_all}\n"));
    yaml.push_str("metrics:\n");
    yaml.push_str(&format!("  total_route_m: {total_line_m:.1}\n"));
    yaml.push_str(&format!("  n_lines: {}\n", lines.len()));
    yaml.push_str(&format!("  n_stations: {}\n", stations.len()));
    yaml.push_str(&format!("  anchor_hit_rate: {anchor_hit:.3}\n"));
    yaml.push_str(&format!("  high_demand_coverage: {coverage_pct:.3}\n"));
    yaml.push_str("  civil_mix_m:\n");
    yaml.push_str(&format!("    at_grade: {at_grade:.1}\n"));
    yaml.push_str(&format!("    elevated: {elevated:.1}\n"));
    yaml.push_str(&format!("    bridge:   {bridge:.1}\n"));
    // Preserved for backward compatibility with existing deployment
    // scripts; always zero under RFC 0011's no-tunnel invariant.
    yaml.push_str("    tunnel:   0.0\n");
    yaml.push_str(&format!(
        "  elevated_fraction: {elevated_fraction:.3}\n"
    ));
    yaml.push_str("gates:\n");
    yaml.push_str("  hard:\n");
    yaml.push_str(&format!("    has_stations:      {hard_has_stations}\n"));
    yaml.push_str(&format!("    length_reasonable: {hard_length_reasonable}\n"));
    yaml.push_str("  soft:\n");
    yaml.push_str(&format!("    coverage_ge_0.30:   {soft_coverage}\n"));
    yaml.push_str(&format!("    anchor_hit_ge_0.20: {soft_anchor_hit}\n"));
    yaml.push_str(&format!("    elevated_le_0.30:   {soft_elevated_ok}\n"));
    yaml.push_str(&format!("    soft_pass_all:      {soft_all}\n"));

    let path = out_dir.join(format!("{slug}.design-quality.yaml"));
    let mut f = fs::File::create(path)?;
    f.write_all(yaml.as_bytes())?;
    Ok(())
}

/// What fraction of cells with demand > 0.5 are within `radius_cells` of
/// any line cell? Cheap distance transform via BFS from line cells.
fn compute_coverage(bundle: &RasterBundle, lines: &[Line], radius_cells: usize) -> f64 {
    let h = bundle.grid.reference.height;
    let w = bundle.grid.reference.width;
    let mut covered = vec![false; h * w];

    for line in lines {
        for &(r, c) in &line.cells {
            let r_min = r.saturating_sub(radius_cells);
            let r_max = (r + radius_cells).min(h - 1);
            let c_min = c.saturating_sub(radius_cells);
            let c_max = (c + radius_cells).min(w - 1);
            let rr2 = (radius_cells * radius_cells) as isize;
            for rr in r_min..=r_max {
                for cc in c_min..=c_max {
                    let dr = rr as isize - r as isize;
                    let dc = cc as isize - c as isize;
                    if dr * dr + dc * dc <= rr2 {
                        covered[rr * w + cc] = true;
                    }
                }
            }
        }
    }

    let mut hi_cells = 0_u64;
    let mut hi_covered = 0_u64;
    for i in 0..(h * w) {
        if bundle.grid.demand[i] >= 0.5 {
            hi_cells += 1;
            if covered[i] {
                hi_covered += 1;
            }
        }
    }
    if hi_cells == 0 {
        return 0.0;
    }
    hi_covered as f64 / hi_cells as f64
}

// ---------------------------------------------------------------------------
// Tests — exercise the RFC 0008/0009/0010 policy helpers in isolation so the
// compatibility matrix stays regression-guarded without spinning the full
// raster + solver pipeline.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use osr_routing::topology::{Line, LineShape};

    #[test]
    fn family_band_boundaries_match_rfc_0008_section_5() {
        assert_eq!(family_for_population(50_000), "tram-2car");
        assert_eq!(family_for_population(300_000), "tram-2car");
        assert_eq!(family_for_population(300_001), "light-metro-3car");
        assert_eq!(family_for_population(1_000_000), "light-metro-3car");
        assert_eq!(family_for_population(1_000_001), "metro-4car");
        assert_eq!(family_for_population(3_000_000), "metro-4car");
        assert_eq!(family_for_population(3_000_001), "metro-6car");
    }

    #[test]
    fn geometry_matches_family_compatibility() {
        // Every family must resolve to a geometry preset that RFC 0009 §10
        // lists as compatible.
        assert_eq!(geometry_for_family("tram-2car"), "standard-urban");
        assert_eq!(geometry_for_family("light-metro-3car"), "standard-urban");
        assert_eq!(geometry_for_family("metro-4car"), "standard-metro");
        assert_eq!(geometry_for_family("metro-6car"), "standard-metro");
    }

    fn st(line: &str, s_m: f64, lat: f64, lon: f64, demand: f32) -> Station {
        Station {
            row: 0,
            col: 0,
            lat,
            lon,
            anchor_id: None,
            anchor_kind: None,
            anchor_name: None,
            line_name: line.to_string(),
            s_m,
            demand,
        }
    }

    fn radial_line(name: &str) -> Line {
        Line {
            name: name.to_string(),
            shape: LineShape::Radial,
            cells: vec![],
            anchor_ids: vec![],
        }
    }

    fn ring_line(name: &str) -> Line {
        Line {
            name: name.to_string(),
            shape: LineShape::Ring,
            cells: vec![],
            anchor_ids: vec![],
        }
    }

    #[test]
    fn terminal_is_first_and_last_of_radial_line() {
        // 3 stations on one radial line — first and last should be terminal.
        let lines = vec![radial_line("L1")];
        let stations = vec![
            st("L1", 0.0, 0.0, 0.0, 0.3),
            st("L1", 1_000.0, 0.01, 0.0, 0.3),
            st("L1", 2_000.0, 0.02, 0.0, 0.3),
        ];
        let a = compute_archetypes(&lines, &stations);
        // Longest s_m terminal wins depot-terminal promotion.
        assert_eq!(a[0], "terminal");
        assert_eq!(a[1], "standard");
        assert_eq!(a[2], "depot-terminal");
    }

    #[test]
    fn ring_has_no_terminal() {
        let lines = vec![ring_line("R1")];
        let stations = vec![
            st("R1", 0.0, 0.0, 0.0, 0.3),
            st("R1", 500.0, 0.005, 0.0, 0.3),
            st("R1", 1_000.0, 0.01, 0.0, 0.3),
        ];
        let a = compute_archetypes(&lines, &stations);
        for arch in &a {
            assert_ne!(*arch, "terminal");
            assert_ne!(*arch, "depot-terminal");
        }
    }

    #[test]
    fn two_nearby_cross_line_stations_are_interchange() {
        // Two lines; one station each within 100 m of each other →
        // both get archetype "interchange" (overrides demand-based).
        let lines = vec![radial_line("L1"), radial_line("L2")];
        let stations = vec![
            st("L1", 0.0, 0.0, 0.0, 0.3),
            // Middle of L1 — this is the interchange candidate.
            st("L1", 1_000.0, 0.001, 0.001, 0.3),
            st("L1", 2_000.0, 0.02, 0.02, 0.3),
            st("L2", 0.0, 0.05, 0.05, 0.3),
            // ~157 m from L1's middle station; should interchange.
            st("L2", 1_000.0, 0.0011, 0.001, 0.3),
            st("L2", 2_000.0, 0.06, 0.06, 0.3),
        ];
        let a = compute_archetypes(&lines, &stations);
        assert_eq!(a[1], "interchange");
        assert_eq!(a[4], "interchange");
    }

    #[test]
    fn demand_picks_major_vs_standard_vs_halt_when_no_override() {
        let lines = vec![radial_line("L1")];
        let stations = vec![
            // First + last will be terminals; middle ones stay demand-based.
            st("L1", 0.0, 0.0, 0.0, 0.3),
            st("L1", 1_000.0, 0.01, 0.0, 0.8),
            st("L1", 2_000.0, 0.02, 0.0, 0.1),
            st("L1", 3_000.0, 0.03, 0.0, 0.5),
            st("L1", 4_000.0, 0.04, 0.0, 0.3),
        ];
        let a = compute_archetypes(&lines, &stations);
        assert_eq!(a[0], "terminal");
        assert_eq!(a[1], "major"); // demand 0.8
        assert_eq!(a[2], "halt"); // demand 0.1
        assert_eq!(a[3], "standard"); // demand 0.5
        assert_eq!(a[4], "depot-terminal"); // farthest endpoint
    }

    #[test]
    fn haversine_recovers_small_distances_under_one_percent() {
        // ~111 m at the equator between lat 0 and lat 0.001.
        let d = haversine_m(0.0, 0.0, 0.001, 0.0);
        assert!(
            (d - 111.0).abs() < 1.0,
            "expected ≈ 111 m, got {d:.2} m"
        );
    }

    // ---- v2 emitter: depot blocks, switches, costs --------------------

    #[test]
    fn fleet_sizing_formula_matches_rfc_0014_samawah_example() {
        // RFC 0014 §4 Samawah example: 12 km line → peak 6, spare 1,
        // cold-reserve 1 → fleet 8 → stalls 10.
        let peak = peak_revenue_trainsets(12_000.0);
        assert_eq!(peak, 6);
        let fleet = fleet_total(peak);
        assert_eq!(fleet, 8);
        assert_eq!(depot_stalls(fleet), 10);
    }

    #[test]
    fn depot_blocks_main_heavy_at_depot_terminal_layup_at_plain_terminal() {
        let lines = vec![radial_line("L1")];
        let stations = vec![
            st("L1", 0.0, 0.0, 0.0, 0.3),
            st("L1", 6_000.0, 0.05, 0.0, 0.3),
            st("L1", 12_000.0, 0.10, 0.0, 0.3),
        ];
        // Mimic compute_archetypes output: first is `terminal`, last
        // is `depot-terminal` (farthest), middle is `standard`.
        let archetypes: Vec<&'static str> = vec!["terminal", "standard", "depot-terminal"];

        let depots = compute_depots(&lines, &stations, &archetypes);
        assert_eq!(depots.len(), 2);
        // depot-terminal → main-heavy.
        assert!(depots.iter().any(|d| d.archetype == "main-heavy"));
        // plain terminal → layup-minimal.
        assert!(depots.iter().any(|d| d.archetype == "layup-minimal"));
        // Every emitted depot has non-zero stalls.
        for d in &depots {
            assert!(d.fleet_stalls > 0);
        }
    }

    #[test]
    fn switches_emit_turnback_at_every_terminal_and_yard_fan_at_depot() {
        let lines = vec![radial_line("L1")];
        let stations = vec![
            st("L1", 0.0, 0.0, 0.0, 0.3),
            st("L1", 12_000.0, 0.10, 0.0, 0.3),
        ];
        let archetypes: Vec<&'static str> = vec!["terminal", "depot-terminal"];
        let depots = compute_depots(&lines, &stations, &archetypes);
        let switches = compute_switches(&stations, &archetypes, &depots);

        // One turnback per terminal archetype = 2 turnbacks.
        let tbs: Vec<_> = switches.iter().filter(|s| s.side == "turnback").collect();
        assert_eq!(tbs.len(), 2);
        // Yard-throat count = depot-terminal's fleet_stalls.
        let yd: Vec<_> = switches.iter().filter(|s| s.side == "yard-throat").collect();
        let dt_stalls = depots.iter().find(|d| d.archetype == "main-heavy").unwrap().fleet_stalls;
        assert_eq!(yd.len() as u32, dt_stalls);
        // Every switch uses no-9-mainline per RFC 0012 §3.
        for s in &switches {
            assert_eq!(s.kit, "no-9-mainline");
        }
    }

    #[test]
    fn cost_estimate_applies_rfc_0011_rates() {
        use osr_routing::civil::CivilSegment;
        let civil_per_line = vec![vec![
            CivilSegment {
                class: CivilClass::AtGrade,
                from_idx: 0,
                to_idx: 10,
                length_m: 10_000.0, // 10 km → 35 M€
            },
            CivilSegment {
                class: CivilClass::Elevated,
                from_idx: 10,
                to_idx: 11,
                length_m: 1_000.0, // 1 km → 18 M€
            },
            CivilSegment {
                class: CivilClass::Bridge,
                from_idx: 11,
                to_idx: 12,
                length_m: 500.0, // 0.5 km → 12.5 M€
            },
        ]];
        let c = compute_costs(&[], &civil_per_line);
        assert!((c.at_grade_eur - 35_000_000.0).abs() < 1.0);
        assert!((c.elevated_eur - 18_000_000.0).abs() < 1.0);
        assert!((c.bridge_eur - 12_500_000.0).abs() < 1.0);
        assert!((c.total_eur - 65_500_000.0).abs() < 1.0);
    }
}
