//! Emit design.toml + corridor.geojson + design-quality.yaml + stations.json.
//!
//! The design.toml we emit is a *superset-ready* document: every station
//! carries lat/lon + anchor metadata; every line carries its cell-space
//! polyline. The recipe in designs/recipes/city-to-design.toml then
//! layers in archetype / kit / profile selections when the Python
//! generator fuses this with the templates.
//!
//! This file never calls anyhow::Error types that would leak solver-side
//! state — all output is purely a projection of the bundle + lines.

use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::Result;
use osr_routing::civil::{CivilClass, CivilSegment};
use osr_routing::raster::RasterBundle;
use osr_routing::station::Station;
use osr_routing::topology::Line;
use serde::Serialize;

pub fn write_all(
    out_dir: &Path,
    slug: &str,
    country: &str,
    climate: Option<&str>,
    profile: Option<&str>,
    population: u64,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
    civil_per_line: &[Vec<CivilSegment>],
) -> Result<()> {
    write_design_toml(out_dir, slug, country, climate, profile, population, bundle, lines, stations)?;
    write_corridor_geojson(out_dir, slug, bundle, lines, stations)?;
    write_stations_json(out_dir, slug, stations)?;
    write_quality_yaml(out_dir, slug, bundle, lines, stations, civil_per_line)?;
    Ok(())
}

// ---- design.toml -----------------------------------------------------

fn write_design_toml(
    out_dir: &Path,
    slug: &str,
    country: &str,
    climate: Option<&str>,
    profile: Option<&str>,
    population: u64,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
) -> Result<()> {
    let mut out = String::new();
    out.push_str("# Auto-generated by osr-design from real OSM data.\n");
    out.push_str("# Do not hand-edit without re-running the recipe; changes will be\n");
    out.push_str("# overwritten on the next pipeline run. Override via\n");
    out.push_str("# designs/recipes/city-to-design.toml rule additions instead.\n\n");

    out.push_str("[city]\n");
    out.push_str(&format!("slug            = \"{slug}\"\n"));
    out.push_str(&format!("country         = \"{country}\"\n"));
    out.push_str(&format!("population      = {population}\n"));
    out.push_str(&format!(
        "bbox            = {{ south = {}, west = {}, north = {}, east = {} }}\n",
        bundle.grid.reference.bbox_south,
        bundle.grid.reference.bbox_west,
        bundle.grid.reference.bbox_north,
        bundle.grid.reference.bbox_east,
    ));
    out.push_str(&format!("centroid_lat    = {}\n", bundle.grid.reference.lat0));
    out.push_str("\n");

    out.push_str("[climate]\n");
    let climate_preset = climate.unwrap_or("temperate-continental");
    out.push_str(&format!("preset          = \"{climate_preset}\"\n\n"));

    if let Some(p) = profile {
        out.push_str("[composition]\n");
        out.push_str(&format!("profile         = \"{p}\"\n\n"));
    }

    // One [[lines]] block per synthesized line.
    for line in lines {
        let length_m = line_length_m(bundle, line);
        out.push_str("[[lines]]\n");
        out.push_str(&format!("name            = \"{}\"\n", line.name));
        out.push_str(&format!("shape           = \"{}\"\n", match line.shape {
            osr_routing::topology::LineShape::Radial => "radial",
            osr_routing::topology::LineShape::Ring => "ring",
        }));
        out.push_str(&format!("length_m        = {length_m:.1}\n"));
        out.push_str(&format!("geometry        = \"standard-urban\"\n\n"));
    }

    // Stations — the critical output. Every one has lat/lon.
    for s in stations {
        let sid = station_id(s);
        out.push_str("[[stations]]\n");
        out.push_str(&format!("id              = \"{sid}\"\n"));
        out.push_str(&format!("line            = \"{}\"\n", s.line_name));
        out.push_str(&format!("lat             = {}\n", s.lat));
        out.push_str(&format!("lon             = {}\n", s.lon));
        out.push_str(&format!("s_m             = {:.1}\n", s.s_m));
        if let Some(k) = s.anchor_kind.as_deref() {
            out.push_str(&format!("anchor_kind     = \"{k}\"\n"));
        }
        if let Some(n) = s.anchor_name.as_deref() {
            out.push_str(&format!(
                "anchor_name     = \"{}\"\n",
                escape_toml_string(n)
            ));
        }
        let demand = s.demand;
        let archetype = if demand > 0.6 {
            "major"
        } else if demand > 0.25 {
            "standard"
        } else {
            "halt"
        };
        out.push_str(&format!("archetype       = \"{archetype}\"\n"));
        out.push_str("\n");
    }

    let path = out_dir.join(format!("{slug}.design.toml"));
    fs::write(&path, out)?;
    Ok(())
}

fn station_id(s: &Station) -> String {
    // Stable ID derived from line + cell. Avoids depending on anchor names
    // (which can be non-ASCII / missing).
    format!("{}-{:04}-{:04}", s.line_name, s.row, s.col)
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn line_length_m(bundle: &RasterBundle, line: &Line) -> f64 {
    let cell_m = bundle.grid.reference.cell_m;
    let mut total = 0.0_f64;
    for pair in line.cells.windows(2) {
        let dr = pair[1].0 as f64 - pair[0].0 as f64;
        let dc = pair[1].1 as f64 - pair[0].1 as f64;
        total += (dr * dr + dc * dc).sqrt() * cell_m;
    }
    total
}

// ---- corridor.geojson ------------------------------------------------

fn write_corridor_geojson(
    out_dir: &Path,
    slug: &str,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
) -> Result<()> {
    let mut features: Vec<serde_json::Value> = Vec::new();

    for line in lines {
        // Decimate polyline to every Nth cell to keep file size reasonable;
        // losing sub-cell detail is fine at 20 m resolution.
        let step = (line.cells.len() / 400).max(1);
        let mut coords: Vec<[f64; 2]> = Vec::new();
        for (i, &(r, c)) in line.cells.iter().enumerate() {
            if i == 0 || i == line.cells.len() - 1 || i % step == 0 {
                let (lat, lon) = bundle.grid.reference.rc_to_latlon(r, c);
                coords.push([lon, lat]);
            }
        }
        features.push(serde_json::json!({
            "type": "Feature",
            "properties": {
                "kind": "line",
                "name": line.name,
                "shape": match line.shape {
                    osr_routing::topology::LineShape::Radial => "radial",
                    osr_routing::topology::LineShape::Ring => "ring",
                },
            },
            "geometry": {
                "type": "LineString",
                "coordinates": coords,
            }
        }));
    }

    for s in stations {
        features.push(serde_json::json!({
            "type": "Feature",
            "properties": {
                "kind": "station",
                "line": s.line_name,
                "anchor_kind": s.anchor_kind,
                "anchor_name": s.anchor_name,
            },
            "geometry": {
                "type": "Point",
                "coordinates": [s.lon, s.lat],
            }
        }));
    }

    let geojson = serde_json::json!({
        "type": "FeatureCollection",
        "features": features,
    });
    let path = out_dir.join(format!("{slug}.corridor.geojson"));
    fs::write(&path, serde_json::to_string_pretty(&geojson)?)?;
    Ok(())
}

// ---- stations.json ---------------------------------------------------

#[derive(Serialize)]
struct StationSummary<'a> {
    id: String,
    line: &'a str,
    lat: f64,
    lon: f64,
    s_m: f64,
    anchor_kind: Option<&'a str>,
    anchor_name: Option<&'a str>,
}

fn write_stations_json(out_dir: &Path, slug: &str, stations: &[Station]) -> Result<()> {
    let rows: Vec<StationSummary> = stations
        .iter()
        .map(|s| StationSummary {
            id: station_id(s),
            line: &s.line_name,
            lat: s.lat,
            lon: s.lon,
            s_m: s.s_m,
            anchor_kind: s.anchor_kind.as_deref(),
            anchor_name: s.anchor_name.as_deref(),
        })
        .collect();
    let path = out_dir.join(format!("{slug}.stations.json"));
    fs::write(&path, serde_json::to_string_pretty(&rows)?)?;
    Ok(())
}

// ---- design-quality.yaml --------------------------------------------
//
// This is the automated gate that lets us ship 500 cities without
// human inspection. Each city gets scored; failing thresholds route the
// city back for retry with different topology parameters.

fn write_quality_yaml(
    out_dir: &Path,
    slug: &str,
    bundle: &RasterBundle,
    lines: &[Line],
    stations: &[Station],
    civil_per_line: &[Vec<CivilSegment>],
) -> Result<()> {
    let total_line_m: f64 = lines.iter().map(|l| line_length_m(bundle, l)).sum();
    let anchor_hit = {
        let hit = stations.iter().filter(|s| s.anchor_id.is_some()).count();
        if stations.is_empty() {
            0.0
        } else {
            hit as f64 / stations.len() as f64
        }
    };

    // Coverage: fraction of high-demand cells within 400m (20 cells at 20m)
    // of any line.
    let coverage_pct = compute_coverage(bundle, lines, 20);

    // Civil class mix.
    let mut at_grade = 0.0_f64;
    let mut elevated = 0.0_f64;
    let mut bridge = 0.0_f64;
    let mut tunnel = 0.0_f64;
    for segs in civil_per_line {
        for s in segs {
            match s.class {
                CivilClass::AtGrade => at_grade += s.length_m,
                CivilClass::Elevated => elevated += s.length_m,
                CivilClass::Bridge => bridge += s.length_m,
                CivilClass::CutAndCoverTunnel | CivilClass::BoredTunnel => tunnel += s.length_m,
            }
        }
    }

    // Quality gates: hard (design is invalid if any fail) vs soft
    // (flagged for review but still shippable).
    //
    // Thresholds calibrated against a 3-city ground truth (Samawah,
    // Nairobi, Lyon). The soft bar lets auto-generated designs ship
    // when they are a reasonable first draft — tuning comes from
    // recipe edits, not per-city interventions.
    let hard_has_stations = !stations.is_empty();
    let hard_length_reasonable = total_line_m >= 3_000.0 && total_line_m <= 500_000.0;
    let hard_all = hard_has_stations && hard_length_reasonable;

    let soft_coverage = coverage_pct >= 0.30;
    let soft_anchor_hit = anchor_hit >= 0.20;
    let soft_all = soft_coverage && soft_anchor_hit;

    // A design "passes" if the hard gates pass. Soft gates surface in the
    // report for triage but do not block scale-up.
    let pass_all = hard_all;

    let mut yaml = String::new();
    yaml.push_str(&format!("slug: {slug}\n"));
    yaml.push_str(&format!("pass: {pass_all}\n"));
    yaml.push_str("metrics:\n");
    yaml.push_str(&format!("  total_route_m: {total_line_m:.1}\n"));
    yaml.push_str(&format!("  n_lines: {}\n", lines.len()));
    yaml.push_str(&format!("  n_stations: {}\n", stations.len()));
    yaml.push_str(&format!("  anchor_hit_rate: {anchor_hit:.3}\n"));
    yaml.push_str(&format!("  high_demand_coverage: {coverage_pct:.3}\n"));
    yaml.push_str("  civil_mix_m:\n");
    yaml.push_str(&format!("    at_grade: {at_grade:.1}\n"));
    yaml.push_str(&format!("    elevated: {elevated:.1}\n"));
    yaml.push_str(&format!("    bridge:   {bridge:.1}\n"));
    yaml.push_str(&format!("    tunnel:   {tunnel:.1}\n"));
    yaml.push_str("gates:\n");
    yaml.push_str("  hard:\n");
    yaml.push_str(&format!("    has_stations:      {hard_has_stations}\n"));
    yaml.push_str(&format!("    length_reasonable: {hard_length_reasonable}\n"));
    yaml.push_str("  soft:\n");
    yaml.push_str(&format!("    coverage_ge_0.30:   {soft_coverage}\n"));
    yaml.push_str(&format!("    anchor_hit_ge_0.20: {soft_anchor_hit}\n"));
    yaml.push_str(&format!("    soft_pass_all:      {soft_all}\n"));

    let path = out_dir.join(format!("{slug}.design-quality.yaml"));
    let mut f = fs::File::create(path)?;
    f.write_all(yaml.as_bytes())?;
    Ok(())
}

/// What fraction of cells with demand > 0.5 are within `radius_cells` of
/// any line cell? Cheap distance transform via BFS from line cells.
fn compute_coverage(bundle: &RasterBundle, lines: &[Line], radius_cells: usize) -> f64 {
    let h = bundle.grid.reference.height;
    let w = bundle.grid.reference.width;
    let mut covered = vec![false; h * w];

    for line in lines {
        for &(r, c) in &line.cells {
            let r_min = r.saturating_sub(radius_cells);
            let r_max = (r + radius_cells).min(h - 1);
            let c_min = c.saturating_sub(radius_cells);
            let c_max = (c + radius_cells).min(w - 1);
            let rr2 = (radius_cells * radius_cells) as isize;
            for rr in r_min..=r_max {
                for cc in c_min..=c_max {
                    let dr = rr as isize - r as isize;
                    let dc = cc as isize - c as isize;
                    if dr * dr + dc * dc <= rr2 {
                        covered[rr * w + cc] = true;
                    }
                }
            }
        }
    }

    let mut hi_cells = 0_u64;
    let mut hi_covered = 0_u64;
    for i in 0..(h * w) {
        if bundle.grid.demand[i] >= 0.5 {
            hi_cells += 1;
            if covered[i] {
                hi_covered += 1;
            }
        }
    }
    if hi_cells == 0 {
        return 0.0;
    }
    hi_covered as f64 / hi_cells as f64
}
