"""End-to-end civil, track, station, and rolling-stock digital twin.

This module deliberately stays usable without FreeCAD.  It defines the
component placements and the interface checks for the native FreeCAD review
document generated by :mod:`osr_mech.freecad_civil_systems_example`.

The document and paired JSON manifest form a deterministic design-reference
twin, not a live operational alignment or a released structural design. Its
zones are separated in plan so reviewers can inspect canonical stations,
turnout, viaduct, complete trains, assets, relationships, and state without
hiding clashes inside a single fused solid.
"""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from typing import Callable

from osr_mech.cad import Axis, Box, Color, Compound, Location, Part
from osr_mech.clearance import reference_dynamic_width_mm, reference_envelope, swept_envelope_part
from osr_mech.civil.guideway_channel_edge import (
    PLATFORM_TO_TOR_HEIGHT_MM,
    guideway_channel_edge_module,
)
from osr_mech.civil.platform_l_unit import UNIT_LENGTH_MM, platform_l_unit
from osr_mech.civil.decked_pi import (
    FLANGE_THICKNESS_MM,
    OVERALL_DEPTH_MM,
    WALKWAY_CASSETTE_WIDTH_MM,
    decked_pi_structural_placeholder,
    walkway_cassette,
)
from osr_mech.civil.slab import (
    AT_GRADE_BASE_THICKNESS_MM,
    AT_GRADE_PLINTH_HEIGHT_MM,
    BASEPLATE_PAD_HEIGHT_MM,
    ELEVATED_BASE_THICKNESS_MM,
    ELEVATED_PLINTH_HEIGHT_MM,
    TRACK_CENTRE_SPACING_MM,
    at_grade_twin_rail_y_positions,
    at_grade_slab_panel,
    elevated_deck_slab_panel,
)
from osr_mech.civil.substructure import GIRDER_CENTRE_SPACING_MM, viaduct_pier
from osr_mech.common import RAIL_GEOMETRY, ConsistFamily, RailProfile, StationArchetype, STANDARD_GAUGE_MM
from osr_mech.station.canopy import station_canopy
from osr_mech.track.rail import rail_bar
from osr_mech.track.turnout import TurnoutTangent, turnout
from osr_mech.rolling_stock.trainset import trainset


GROUND_STATION_X_MM = 0.0
GROUND_STATION_LENGTH_MM = 60_000.0
JUNCTION_X_MM = 66_000.0

VIADUCT_START_X_MM = 110_000.0
VIADUCT_SPAN_MM = 25_000.0
VIADUCT_APPROACH_SPANS = 3
ELEVATED_STATION_X_MM = VIADUCT_START_X_MM + VIADUCT_APPROACH_SPANS * VIADUCT_SPAN_MM
ELEVATED_STATION_LENGTH_MM = 60_000.0
VIADUCT_DEPARTURE_X_MM = ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM
VIADUCT_DEPARTURE_SPANS = 3

# 8 m column + 1.2 m cap + 0.1 m bearing.
PIER_BEARING_TOP_Z_MM = 9_300.0
PI_BEAM_BASE_Z_MM = PIER_BEARING_TOP_Z_MM
ELEVATED_TRACK_SUPPORT_Z_MM = PI_BEAM_BASE_Z_MM + OVERALL_DEPTH_MM

RAIL_HEIGHT_MM = RAIL_GEOMETRY[RailProfile.UIC_60E1].height_mm
AT_GRADE_RAIL_BASE_LOCAL_Z_MM = (
    AT_GRADE_BASE_THICKNESS_MM + AT_GRADE_PLINTH_HEIGHT_MM + BASEPLATE_PAD_HEIGHT_MM
)
ELEVATED_RAIL_BASE_LOCAL_Z_MM = (
    ELEVATED_BASE_THICKNESS_MM + ELEVATED_PLINTH_HEIGHT_MM + BASEPLATE_PAD_HEIGHT_MM
)

# The at-grade edge module walking surface is at z=620 mm.  Lower the track
# package so its rail head is exactly 350 mm below that surface.
GROUND_PLATFORM_SURFACE_Z_MM = 620.0
GROUND_TOR_Z_MM = GROUND_PLATFORM_SURFACE_Z_MM - PLATFORM_TO_TOR_HEIGHT_MM
GROUND_SLAB_BASE_Z_MM = GROUND_TOR_Z_MM - RAIL_HEIGHT_MM - AT_GRADE_RAIL_BASE_LOCAL_Z_MM
GROUND_RAIL_BASE_Z_MM = GROUND_TOR_Z_MM - RAIL_HEIGHT_MM

ELEVATED_RAIL_BASE_Z_MM = ELEVATED_TRACK_SUPPORT_Z_MM + ELEVATED_RAIL_BASE_LOCAL_Z_MM
ELEVATED_TOR_Z_MM = ELEVATED_RAIL_BASE_Z_MM + RAIL_HEIGHT_MM
ELEVATED_PLATFORM_SURFACE_Z_MM = ELEVATED_TOR_Z_MM + PLATFORM_TO_TOR_HEIGHT_MM

PLATFORM_HORIZONTAL_GAP_MM = 75.0
GROUND_OUTER_TRACK_Y_MM = TRACK_CENTRE_SPACING_MM / 2.0
ELEVATED_OUTER_TRACK_Y_MM = GIRDER_CENTRE_SPACING_MM / 2.0
GROUND_PLATFORM_EDGE_Y_MM = (
    GROUND_OUTER_TRACK_Y_MM + reference_dynamic_width_mm() / 2.0 + PLATFORM_HORIZONTAL_GAP_MM
)
# The guideway module's closest physical face is 425 mm inboard of its
# placement origin. Keep the controlled platform edge at the datum above while
# offsetting the complete coping/drain module far enough outboard.
GROUND_GUIDEWAY_EDGE_ORIGIN_Y_MM = GROUND_PLATFORM_EDGE_Y_MM + 425.0
ELEVATED_PLATFORM_EDGE_Y_MM = (
    ELEVATED_OUTER_TRACK_Y_MM + reference_dynamic_width_mm() / 2.0 + PLATFORM_HORIZONTAL_GAP_MM
)

ELEVATED_PLATFORM_DEPTH_MM = 2_500.0
ELEVATED_STATION_DECK_WIDTH_MM = 2.0 * (
    ELEVATED_PLATFORM_EDGE_Y_MM + ELEVATED_PLATFORM_DEPTH_MM
)
# The station interface must reach the same structural support datum as the
# adjoining Pi-beam, not merely copy the upper flange thickness.
ELEVATED_STATION_DECK_THICKNESS_MM = OVERALL_DEPTH_MM

DIGITAL_TWIN_SCHEMA = "org.opensourcerail.civil-rolling-stock-twin.v1"
DIGITAL_TWIN_SNAPSHOT_ID = "OSR-DT-DESIGN-REFERENCE-001"

ZONE_ASSET_IDS = {
    "01 At-grade ground station": "OSR-DT-ZONE-STN-GROUND-001",
    "02 At-grade junction": "OSR-DT-ZONE-JCT-001",
    "03 Viaduct approaches and substructure": "OSR-DT-ZONE-VIA-001",
    "04 Elevated station": "OSR-DT-ZONE-STN-ELEVATED-001",
    "05 Rolling stock": "OSR-DT-ZONE-RST-001",
}


Builder = Callable[[], Part | Compound]


@dataclass(frozen=True)
class IntegrationComponent:
    """One independently inspectable source component in the review site."""

    zone: str
    label: str
    source: str
    builder: Builder
    translation_mm: tuple[float, float, float] = (0.0, 0.0, 0.0)
    rotation_z_deg: float = 0.0
    transparency: int = 0

    def build(self) -> Part | Compound:
        item = self.builder()
        if self.rotation_z_deg:
            item = item.rotate(Axis.Z, self.rotation_z_deg)
        if self.translation_mm != (0.0, 0.0, 0.0):
            item = item.translate(self.translation_mm)
        item.label = self.label
        return item


@dataclass(frozen=True)
class IntegrationMetric:
    """Structured target and observation for one numeric interface check."""

    name: str
    observed_value_m: float
    target_value_m: float
    measure_type: str = "IfcLengthMeasure"
    unit: str = "m"
    benchmark: str = "EQUALTO"
    reference_path_status: str = "derived multi-object geometry; no single IFC attribute path"


@dataclass(frozen=True)
class IntegrationCheck:
    name: str
    passed: bool
    detail: str
    metric: IntegrationMetric | None = None


def asset_id_for_component(component: IntegrationComponent) -> str:
    """Stable identifier derived from the component's semantic identity."""

    if component.label == "Ground-station complete light-metro trainset":
        return "OSR-LM3-TEST-001"
    if component.label == "Elevated-station complete light-metro trainset":
        return "OSR-LM3-TEST-002"
    digest = hashlib.sha256(f"{component.zone}|{component.label}".encode()).hexdigest()[:10].upper()
    return f"OSR-DT-{digest}"


def asset_class_for_component(component: IntegrationComponent) -> str:
    source = component.source
    if "rolling_stock.trainset" in source:
        return "rolling-stock.trainset"
    if "turnout" in source:
        return "track.turnout"
    if "rail_bar" in source:
        return "track.rail"
    if "pier" in source:
        return "civil.pier"
    if "decked_pi" in source:
        return "civil.decked-pi-beam"
    if "walkway_cassette" in source:
        return "civil.walkway-cassette"
    if "slab_panel" in source:
        return "civil.trackform"
    if "station_canopy" in source:
        return "station.solar-canopy"
    if "platform" in source or "guideway_channel_edge" in source:
        return "station.platform-interface"
    if "kinematic" in source or "kinematic envelope" in component.label.lower():
        return "clearance.reference-envelope"
    if "station_deck" in source:
        return "civil.station-deck-interface"
    return "infrastructure.component"


def operational_state_for_component(component: IntegrationComponent) -> dict[str, object]:
    """Design-reference state carried by both FreeCAD and JSON twins."""

    asset_class = asset_class_for_component(component)
    if component.label == "Ground-station complete light-metro trainset":
        return {
            "mode": "stationary-dwell-charging",
            "speed_kmh": 0.0,
            "soc_percent": 82.0,
            "doors": "platform-side-enabled",
            "occupancy_passengers": 120,
            "health": "nominal",
            "deployed_interfaces": ["gap-filler", "side-pin-charge-contact"],
        }
    if component.label == "Elevated-station complete light-metro trainset":
        return {
            "mode": "stationary-dwell",
            "speed_kmh": 0.0,
            "soc_percent": 64.0,
            "doors": "platform-side-enabled",
            "occupancy_passengers": 75,
            "health": "nominal",
            "deployed_interfaces": ["gap-filler"],
        }
    if asset_class == "track.turnout":
        return {"availability": "available", "position": "normal", "locked": True, "health": "nominal"}
    if asset_class == "station.solar-canopy":
        return {"availability": "available", "pv_generation_kw": 0.0, "health": "nominal"}
    if asset_class == "clearance.reference-envelope":
        return {"mode": "design-reference", "applicability": "tangent-running-state"}
    return {"availability": "available", "health": "nominal", "lifecycle_state": "design-reference"}


def _platform_l_run() -> Compound:
    units = int(ELEVATED_STATION_LENGTH_MM / UNIT_LENGTH_MM)
    return Compound(
        label=f"Elevated platform L-unit run ({units} match-cast units)",
        children=[platform_l_unit().translate((index * UNIT_LENGTH_MM, 0.0, 0.0)) for index in range(units)],
    )


def _walkway_run(length_mm: float, side: float) -> Compound:
    count = int(math.ceil(length_mm / 6_000.0))
    children = []
    for index in range(count):
        segment_length_m = min(6_000.0, length_mm - index * 6_000.0) / 1_000.0
        cassette = walkway_cassette(segment_length_m)
        if side < 0:
            cassette = cassette.rotate(Axis.X, 180.0)
        children.append(cassette.translate((index * 6_000.0, 0.0, 0.0)))
    return Compound(label="Modular outer evacuation walkway run", children=children)


def _elevated_station_deck_interface() -> Part:
    """Station-specific deck coordination envelope.

    This is intentionally an interface envelope rather than a released
    structural product: project loading, reinforcement, diaphragms, bearings,
    seismic restraint, and erection design remain deployment calculations.
    """

    deck = Box(
        ELEVATED_STATION_LENGTH_MM,
        ELEVATED_STATION_DECK_WIDTH_MM,
        ELEVATED_STATION_DECK_THICKNESS_MM,
    ).locate(
        Location(
            (
                ELEVATED_STATION_LENGTH_MM / 2.0,
                0.0,
                ELEVATED_STATION_DECK_THICKNESS_MM / 2.0,
            )
        )
    )
    deck.label = "Project-specific elevated station deck interface envelope"
    deck.color = Color(0.62, 0.66, 0.70)
    return deck


def _component(
    zone: str,
    label: str,
    source: str,
    builder: Builder,
    translation_mm: tuple[float, float, float] = (0.0, 0.0, 0.0),
    *,
    rotation_z_deg: float = 0.0,
    transparency: int = 0,
) -> IntegrationComponent:
    return IntegrationComponent(
        zone=zone,
        label=label,
        source=source,
        builder=builder,
        translation_mm=translation_mm,
        rotation_z_deg=rotation_z_deg,
        transparency=transparency,
    )


def integration_components() -> tuple[IntegrationComponent, ...]:
    """Return the deterministic component manifest for the review document."""

    items: list[IntegrationComponent] = []

    ground = "01 At-grade ground station"
    for side, track_y in (("-Y", -GROUND_OUTER_TRACK_Y_MM), ("+Y", GROUND_OUTER_TRACK_Y_MM)):
        items.append(
            _component(
                ground,
                f"60 m {side} OSR-ST6 single-track panel run",
                "civil.at_grade_slab_panel(length_mm=60000)",
                partial(at_grade_slab_panel, GROUND_STATION_LENGTH_MM),
                (GROUND_STATION_X_MM, track_y, GROUND_SLAB_BASE_Z_MM),
            )
        )
    for index, rail_y in enumerate(at_grade_twin_rail_y_positions(), start=1):
        items.append(
            _component(
                ground,
                f"Ground-station UIC 60E1 running rail {index}",
                "track.rail_bar(UIC_60E1, length_mm=60000)",
                partial(rail_bar, RailProfile.UIC_60E1, GROUND_STATION_LENGTH_MM),
                (GROUND_STATION_X_MM, rail_y, GROUND_RAIL_BASE_Z_MM),
            )
        )
    items.extend(
        [
            _component(
                ground,
                "Ground-station +Y guideway edge, coping, tactile carrier, and drain",
                "civil.guideway_channel_edge_module(length_mm=60000)",
                partial(guideway_channel_edge_module, GROUND_STATION_LENGTH_MM),
                (GROUND_STATION_X_MM, GROUND_GUIDEWAY_EDGE_ORIGIN_Y_MM, 0.0),
            ),
            _component(
                ground,
                "Ground-station -Y guideway edge, coping, tactile carrier, and drain",
                "civil.guideway_channel_edge_module(length_mm=60000), mirrored in plan",
                partial(guideway_channel_edge_module, GROUND_STATION_LENGTH_MM),
                (
                    GROUND_STATION_X_MM + GROUND_STATION_LENGTH_MM,
                    -GROUND_GUIDEWAY_EDGE_ORIGIN_Y_MM,
                    0.0,
                ),
                rotation_z_deg=180.0,
            ),
            _component(
                ground,
                "Ground-station +Y standard solar canopy",
                "station.station_canopy(standard, light-metro-3car)",
                partial(station_canopy, StationArchetype.STANDARD, ConsistFamily.LIGHT_METRO_3CAR),
                (GROUND_STATION_X_MM, GROUND_PLATFORM_EDGE_Y_MM, GROUND_PLATFORM_SURFACE_Z_MM),
            ),
            _component(
                ground,
                "Ground-station -Y standard solar canopy",
                "station.station_canopy(standard, light-metro-3car), mirrored in plan",
                partial(station_canopy, StationArchetype.STANDARD, ConsistFamily.LIGHT_METRO_3CAR),
                (
                    GROUND_STATION_X_MM + GROUND_STATION_LENGTH_MM,
                    -GROUND_PLATFORM_EDGE_Y_MM,
                    GROUND_PLATFORM_SURFACE_Z_MM,
                ),
                rotation_z_deg=180.0,
            ),
            _component(
                ground,
                "Ground-station tangent kinematic envelope",
                "clearance.swept_envelope_part(reference_envelope())",
                partial(swept_envelope_part, reference_envelope()),
                (GROUND_STATION_X_MM + GROUND_STATION_LENGTH_MM / 2.0, -GROUND_OUTER_TRACK_Y_MM, GROUND_TOR_Z_MM),
                transparency=78,
            ),
        ]
    )

    junction = "02 At-grade junction"
    # The turnout source uses a simplified 40 mm rail section.  Align its rail
    # head with the adjoining station top-of-rail datum, rather than its foot.
    turnout_base_z = GROUND_TOR_Z_MM - 40.0
    items.append(
        _component(
            junction,
            "Controlled 1:9 at-grade turnout and diverging junction",
            "track.turnout(T_1_9)",
            partial(turnout, TurnoutTangent.T_1_9),
            (JUNCTION_X_MM, -GROUND_OUTER_TRACK_Y_MM, turnout_base_z),
        )
    )

    viaduct = "03 Viaduct approaches and substructure"
    span_starts = [
        VIADUCT_START_X_MM + index * VIADUCT_SPAN_MM
        for index in range(VIADUCT_APPROACH_SPANS)
    ] + [
        VIADUCT_DEPARTURE_X_MM + index * VIADUCT_SPAN_MM
        for index in range(VIADUCT_DEPARTURE_SPANS)
    ]
    for span_index, span_x in enumerate(span_starts, start=1):
        for side, track_y in (("-Y", -ELEVATED_OUTER_TRACK_Y_MM), ("+Y", ELEVATED_OUTER_TRACK_Y_MM)):
            prefix = f"Viaduct span {span_index} {side}"
            items.extend(
                [
                    _component(
                        viaduct,
                        f"{prefix} OSR-Pi25 decked beam",
                        "civil.decked_pi_structural_placeholder(span_m=25)",
                        partial(decked_pi_structural_placeholder, 25.0),
                        (span_x, track_y, PI_BEAM_BASE_Z_MM),
                    ),
                    _component(
                        viaduct,
                        f"{prefix} modular outer evacuation walkway",
                        "civil.walkway_cassette(length_m=6) repeated",
                        partial(_walkway_run, VIADUCT_SPAN_MM, side=-1.0 if side == "-Y" else 1.0),
                        (
                            span_x,
                            track_y
                            + (-1.0 if side == "-Y" else 1.0)
                            * (1_450.0 + WALKWAY_CASSETTE_WIDTH_MM / 2.0),
                            ELEVATED_TRACK_SUPPORT_Z_MM,
                        ),
                    ),
                    _component(
                        viaduct,
                        f"{prefix} 25 m alignment layer, plinths, seats, and service trough",
                        "civil.elevated_deck_slab_panel(length_mm=25000)",
                        partial(elevated_deck_slab_panel, VIADUCT_SPAN_MM),
                        (span_x, track_y, ELEVATED_TRACK_SUPPORT_Z_MM),
                    ),
                    _component(
                        viaduct,
                        f"{prefix} UIC 60E1 rail -Y",
                        "track.rail_bar(UIC_60E1, length_mm=25000)",
                        partial(rail_bar, RailProfile.UIC_60E1, VIADUCT_SPAN_MM),
                        (span_x, track_y - STANDARD_GAUGE_MM / 2.0, ELEVATED_RAIL_BASE_Z_MM),
                    ),
                    _component(
                        viaduct,
                        f"{prefix} UIC 60E1 rail +Y",
                        "track.rail_bar(UIC_60E1, length_mm=25000)",
                        partial(rail_bar, RailProfile.UIC_60E1, VIADUCT_SPAN_MM),
                        (span_x, track_y + STANDARD_GAUGE_MM / 2.0, ELEVATED_RAIL_BASE_Z_MM),
                    ),
                ]
            )

    pier_x_positions = (
        VIADUCT_START_X_MM,
        VIADUCT_START_X_MM + VIADUCT_SPAN_MM,
        VIADUCT_START_X_MM + 2.0 * VIADUCT_SPAN_MM,
        ELEVATED_STATION_X_MM,
        ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM / 2.0,
        VIADUCT_DEPARTURE_X_MM,
        VIADUCT_DEPARTURE_X_MM + VIADUCT_SPAN_MM,
        VIADUCT_DEPARTURE_X_MM + 2.0 * VIADUCT_SPAN_MM,
        VIADUCT_DEPARTURE_X_MM + 3.0 * VIADUCT_SPAN_MM,
    )
    for index, pier_x in enumerate(pier_x_positions, start=1):
        items.append(
            _component(
                viaduct,
                f"Shared double-track pier {index}",
                "civil.viaduct_pier(height_m=8, foundation='interface-only')",
                partial(viaduct_pier, 8.0, "interface-only"),
                (pier_x, 0.0, 0.0),
            )
        )

    elevated = "04 Elevated station"
    items.append(
        _component(
            elevated,
            "60 m project-specific elevated station deck interface envelope",
            "integration.elevated_station_deck_interface (not a released structural product)",
            _elevated_station_deck_interface,
            (ELEVATED_STATION_X_MM, 0.0, PI_BEAM_BASE_Z_MM),
        )
    )
    for side, track_y in (("-Y", -ELEVATED_OUTER_TRACK_Y_MM), ("+Y", ELEVATED_OUTER_TRACK_Y_MM)):
        items.append(
            _component(
                elevated,
                f"Elevated-station {side} 60 m alignment layer, plinths, seats, and service trough",
                "civil.elevated_deck_slab_panel(length_mm=60000)",
                partial(elevated_deck_slab_panel, ELEVATED_STATION_LENGTH_MM),
                (ELEVATED_STATION_X_MM, track_y, ELEVATED_TRACK_SUPPORT_Z_MM),
            )
        )
        for rail_side, offset_y in (("-Y", -STANDARD_GAUGE_MM / 2.0), ("+Y", STANDARD_GAUGE_MM / 2.0)):
            items.append(
                _component(
                    elevated,
                    f"Elevated-station {side} UIC 60E1 rail {rail_side}",
                    "track.rail_bar(UIC_60E1, length_mm=60000)",
                    partial(rail_bar, RailProfile.UIC_60E1, ELEVATED_STATION_LENGTH_MM),
                    (ELEVATED_STATION_X_MM, track_y + offset_y, ELEVATED_RAIL_BASE_Z_MM),
                )
            )

    elevated_platform_base_z = ELEVATED_PLATFORM_SURFACE_Z_MM - 1_100.0
    items.extend(
        [
            _component(
                elevated,
                "Elevated-station +Y platform run, 20 precast L-units",
                "civil.platform_l_unit x20",
                _platform_l_run,
                (ELEVATED_STATION_X_MM, ELEVATED_PLATFORM_EDGE_Y_MM, elevated_platform_base_z),
            ),
            _component(
                elevated,
                "Elevated-station -Y platform run, 20 precast L-units",
                "civil.platform_l_unit x20, mirrored in plan",
                _platform_l_run,
                (
                    ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM,
                    -ELEVATED_PLATFORM_EDGE_Y_MM,
                    elevated_platform_base_z,
                ),
                rotation_z_deg=180.0,
            ),
            _component(
                elevated,
                "Elevated-station +Y standard solar canopy",
                "station.station_canopy(standard, light-metro-3car)",
                partial(station_canopy, StationArchetype.STANDARD, ConsistFamily.LIGHT_METRO_3CAR),
                (ELEVATED_STATION_X_MM, ELEVATED_PLATFORM_EDGE_Y_MM, ELEVATED_PLATFORM_SURFACE_Z_MM),
            ),
            _component(
                elevated,
                "Elevated-station -Y standard solar canopy",
                "station.station_canopy(standard, light-metro-3car), mirrored in plan",
                partial(station_canopy, StationArchetype.STANDARD, ConsistFamily.LIGHT_METRO_3CAR),
                (
                    ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM,
                    -ELEVATED_PLATFORM_EDGE_Y_MM,
                    ELEVATED_PLATFORM_SURFACE_Z_MM,
                ),
                rotation_z_deg=180.0,
            ),
            _component(
                elevated,
                "Elevated-station tangent kinematic envelope",
                "clearance.swept_envelope_part(reference_envelope())",
                partial(swept_envelope_part, reference_envelope()),
                (
                    ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM / 2.0,
                    ELEVATED_OUTER_TRACK_Y_MM,
                    ELEVATED_TOR_Z_MM,
                ),
                transparency=78,
            ),
        ]
    )

    rolling_stock = "05 Rolling stock"
    complete_lm3 = partial(trainset, ConsistFamily.LIGHT_METRO_3CAR)
    items.extend(
        [
            _component(
                rolling_stock,
                "Ground-station complete light-metro trainset",
                "rolling_stock.trainset(light-metro-3car; physical geometry plus interface reservations)",
                complete_lm3,
                (
                    GROUND_STATION_X_MM + GROUND_STATION_LENGTH_MM / 2.0,
                    -GROUND_OUTER_TRACK_Y_MM,
                    GROUND_TOR_Z_MM,
                ),
            ),
            _component(
                rolling_stock,
                "Elevated-station complete light-metro trainset",
                "rolling_stock.trainset(light-metro-3car; physical geometry plus interface reservations)",
                complete_lm3,
                (
                    ELEVATED_STATION_X_MM + ELEVATED_STATION_LENGTH_MM / 2.0,
                    ELEVATED_OUTER_TRACK_Y_MM,
                    ELEVATED_TOR_Z_MM,
                ),
            ),
        ]
    )

    return tuple(items)


def integration_checks() -> tuple[IntegrationCheck, ...]:
    """Evaluate the controlled interface datums used by the example."""

    pier_top = viaduct_pier(8.0).bounding_box().max.Z
    station_deck_top = PI_BEAM_BASE_Z_MM + ELEVATED_STATION_DECK_THICKNESS_MM
    ground_gap = GROUND_PLATFORM_EDGE_Y_MM - (
        GROUND_OUTER_TRACK_Y_MM + reference_dynamic_width_mm() / 2.0
    )
    elevated_gap = ELEVATED_PLATFORM_EDGE_Y_MM - (
        ELEVATED_OUTER_TRACK_Y_MM + reference_dynamic_width_mm() / 2.0
    )
    components = integration_components()
    zones = {item.zone for item in components}
    required_zones = {
        "01 At-grade ground station",
        "02 At-grade junction",
        "03 Viaduct approaches and substructure",
        "04 Elevated station",
        "05 Rolling stock",
    }

    return (
        IntegrationCheck(
            "pier-bearing-to-girder-soffit",
            abs(pier_top - PI_BEAM_BASE_Z_MM) < 1e-6,
            f"pier/bearing top {pier_top:.1f} mm; pi-beam soffit {PI_BEAM_BASE_Z_MM:.1f} mm",
            IntegrationMetric(
                "Pier bearing top equals girder soffit",
                pier_top / 1_000.0,
                PI_BEAM_BASE_Z_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "viaduct-to-station-track-support-datum",
            abs(station_deck_top - ELEVATED_TRACK_SUPPORT_Z_MM) < 1e-6,
            f"both structural track-support surfaces are z={ELEVATED_TRACK_SUPPORT_Z_MM:.1f} mm",
            IntegrationMetric(
                "Station and viaduct track-support datum",
                station_deck_top / 1_000.0,
                ELEVATED_TRACK_SUPPORT_Z_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "ground-platform-vertical-datum",
            abs((GROUND_PLATFORM_SURFACE_Z_MM - GROUND_TOR_Z_MM) - PLATFORM_TO_TOR_HEIGHT_MM) < 1e-6,
            f"platform is {GROUND_PLATFORM_SURFACE_Z_MM - GROUND_TOR_Z_MM:.1f} mm above top of rail",
            IntegrationMetric(
                "Ground platform height above top of rail",
                (GROUND_PLATFORM_SURFACE_Z_MM - GROUND_TOR_Z_MM) / 1_000.0,
                PLATFORM_TO_TOR_HEIGHT_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "elevated-platform-vertical-datum",
            abs((ELEVATED_PLATFORM_SURFACE_Z_MM - ELEVATED_TOR_Z_MM) - PLATFORM_TO_TOR_HEIGHT_MM) < 1e-6,
            f"platform is {ELEVATED_PLATFORM_SURFACE_Z_MM - ELEVATED_TOR_Z_MM:.1f} mm above top of rail",
            IntegrationMetric(
                "Elevated platform height above top of rail",
                (ELEVATED_PLATFORM_SURFACE_Z_MM - ELEVATED_TOR_Z_MM) / 1_000.0,
                PLATFORM_TO_TOR_HEIGHT_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "ground-platform-horizontal-envelope-gap",
            abs(ground_gap - PLATFORM_HORIZONTAL_GAP_MM) < 1e-6,
            f"dynamic-envelope-to-platform gap is {ground_gap:.1f} mm",
            IntegrationMetric(
                "Ground dynamic-envelope to platform gap",
                ground_gap / 1_000.0,
                PLATFORM_HORIZONTAL_GAP_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "elevated-platform-horizontal-envelope-gap",
            abs(elevated_gap - PLATFORM_HORIZONTAL_GAP_MM) < 1e-6,
            f"dynamic-envelope-to-platform gap is {elevated_gap:.1f} mm",
            IntegrationMetric(
                "Elevated dynamic-envelope to platform gap",
                elevated_gap / 1_000.0,
                PLATFORM_HORIZONTAL_GAP_MM / 1_000.0,
            ),
        ),
        IntegrationCheck(
            "requested-system-zones-present",
            required_zones <= zones,
            f"{len(components)} source components across {len(zones)} required zones",
        ),
        IntegrationCheck(
            "junction-turnout-present",
            any("turnout" in item.source for item in components),
            "controlled 1:9 turnout is included as an independently inspectable component",
        ),
        IntegrationCheck(
            "complete-rolling-stock-present",
            sum("rolling_stock.trainset" in item.source for item in components) == 2,
            "complete three-car light-metro trainsets occupy the ground and elevated station tracks",
        ),
    )


def assert_integration_checks() -> tuple[IntegrationCheck, ...]:
    checks = integration_checks()
    failures = [check for check in checks if not check.passed]
    if failures:
        detail = "; ".join(f"{check.name}: {check.detail}" for check in failures)
        raise ValueError(f"civil systems integration checks failed: {detail}")
    return checks


def digital_twin_manifest(
    *,
    model_path: Path | None = None,
    native_clash_checks: tuple[str, ...] = (),
) -> dict[str, object]:
    """Build the portable asset/state snapshot paired with the FCStd model."""

    components = integration_components()
    component_assets: list[dict[str, object]] = []
    relationships: list[dict[str, str]] = []
    for component in components:
        asset_id = asset_id_for_component(component)
        zone_id = ZONE_ASSET_IDS[component.zone]
        component_assets.append(
            {
                "asset_id": asset_id,
                "asset_class": asset_class_for_component(component),
                "name": component.label,
                "parent_asset_id": zone_id,
                "source_geometry": component.source,
                "geometry_role": (
                    "physical-plus-interface-reservations"
                    if "rolling_stock.trainset" in component.source
                    else "physical-review-geometry"
                ),
                "transform": {
                    "translation_mm": list(component.translation_mm),
                    "rotation_z_deg": component.rotation_z_deg,
                },
                "state": operational_state_for_component(component),
            }
        )
        relationships.append(
            {"subject": asset_id, "predicate": "contained-by", "object": zone_id}
        )

    by_label = {component.label: asset_id_for_component(component) for component in components}
    relationships.extend(
        [
            {
                "subject": "OSR-LM3-TEST-001",
                "predicate": "occupies",
                "object": ZONE_ASSET_IDS["01 At-grade ground station"],
            },
            {
                "subject": "OSR-LM3-TEST-001",
                "predicate": "bounded-by-running-envelope",
                "object": by_label["Ground-station tangent kinematic envelope"],
            },
            {
                "subject": "OSR-LM3-TEST-002",
                "predicate": "occupies",
                "object": ZONE_ASSET_IDS["04 Elevated station"],
            },
            {
                "subject": "OSR-LM3-TEST-002",
                "predicate": "bounded-by-running-envelope",
                "object": by_label["Elevated-station tangent kinematic envelope"],
            },
        ]
    )

    zones = [
        {
            "asset_id": asset_id,
            "asset_class": "digital-twin.zone",
            "name": zone,
            "state": {"availability": "available", "lifecycle_state": "design-reference"},
        }
        for zone, asset_id in ZONE_ASSET_IDS.items()
    ]
    model: dict[str, object] = {
        "format": "FreeCAD FCStd",
        "file": model_path.name if model_path else "civil-systems-integration-test.FCStd",
    }
    if model_path is not None:
        model["sha256"] = hashlib.sha256(model_path.read_bytes()).hexdigest()
        model["size_bytes"] = model_path.stat().st_size

    checks = assert_integration_checks()
    return {
        "schema": DIGITAL_TWIN_SCHEMA,
        "snapshot": {
            "snapshot_id": DIGITAL_TWIN_SNAPSHOT_ID,
            "kind": "deterministic-design-reference",
            "live_telemetry": False,
            "state_semantics": "initial conditions compatible with OCC/CBM telemetry; not a live feed",
        },
        "coordinate_system": {
            "name": "OSR integration-site local engineering grid",
            "units": "millimetres",
            "axes": {"x": "traffic/chainage", "y": "transverse-left", "z": "vertical-up"},
            "origin": "ground-station west end at rail-site local datum",
        },
        "model": model,
        "zones": zones,
        "assets": component_assets,
        "relationships": relationships,
        "validation": {
            "interface_checks": [
                {
                    "name": check.name,
                    "passed": check.passed,
                    "detail": check.detail,
                    "metric": (
                        {
                            "name": check.metric.name,
                            "observed_value_m": check.metric.observed_value_m,
                            "target_value_m": check.metric.target_value_m,
                            "measure_type": check.metric.measure_type,
                            "unit": check.metric.unit,
                            "benchmark": check.metric.benchmark,
                            "reference_path_status": check.metric.reference_path_status,
                        }
                        if check.metric
                        else None
                    ),
                }
                for check in checks
            ],
            "native_clearance_clash_checks": list(native_clash_checks),
        },
        "limitations": [
            "The at-grade, junction, and elevated areas are separated review zones, not one released vertical alignment.",
            "The elevated station deck is a coordination envelope pending project structural release.",
            "Rolling-stock geometry includes physical parts and nonphysical interface/reservation overlays.",
            "Operational values are deterministic design-reference state, not live telemetry.",
        ],
    }


def write_digital_twin_manifest(
    path: Path,
    *,
    model_path: Path,
    native_clash_checks: tuple[str, ...],
) -> None:
    payload = digital_twin_manifest(
        model_path=model_path,
        native_clash_checks=native_clash_checks,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


__all__ = [
    "ELEVATED_PLATFORM_SURFACE_Z_MM",
    "ELEVATED_STATION_X_MM",
    "ELEVATED_TOR_Z_MM",
    "GROUND_PLATFORM_SURFACE_Z_MM",
    "GROUND_TOR_Z_MM",
    "IntegrationCheck",
    "IntegrationComponent",
    "PLATFORM_HORIZONTAL_GAP_MM",
    "ZONE_ASSET_IDS",
    "asset_class_for_component",
    "asset_id_for_component",
    "assert_integration_checks",
    "digital_twin_manifest",
    "integration_checks",
    "integration_components",
    "operational_state_for_component",
    "write_digital_twin_manifest",
]
