"""Compute summary statistics for a city design.

Used for:
- Regenerating the §3.4 system-totals table in the deployment RFC.
- CI drift-detection: fail the test if RFC prose contradicts design.toml.
- One-line queries from a shell: `python -m osr_scenario.stats`.
"""

from __future__ import annotations

import argparse
import math
import tomllib
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DesignStats:
    slug: str
    name: str
    line_count: int
    unique_station_count: int
    route_km: float
    revenue_fleet: int
    spare_fleet: int
    cold_reserve_fleet: int
    total_fleet: int
    depot_count: int
    interchange_count: int  # unique stations that appear on ≥ 2 lines
    peak_headway_min: float

    @property
    def total_with_reserve(self) -> int:
        return self.revenue_fleet + self.spare_fleet + self.cold_reserve_fleet

    def as_markdown_table(self) -> str:
        lines = [
            "| Metric | Value |",
            "|---|---|",
            f"| Route-km (double track) | ~{self.route_km:.0f} km |",
            f"| Stations (unique) | {self.unique_station_count} |",
            f"| Lines | {self.line_count} |",
            f"| Multi-line interchanges | {self.interchange_count} |",
            f"| Fleet (revenue) | {self.revenue_fleet} × trainsets |",
            f"| Fleet (spare + cold-reserve) | {self.spare_fleet + self.cold_reserve_fleet} × trainsets |",
            f"| Fleet (total) | {self.total_with_reserve} × trainsets |",
            f"| Depots | {self.depot_count} |",
            f"| Best peak headway | {self.peak_headway_min:.0f} min |",
        ]
        return "\n".join(lines)


def compute_stats(design_path: Path) -> DesignStats:
    doc = tomllib.loads(design_path.read_text())

    # Identifier resolution. The rust `osr-design` emitter writes
    # `[city] slug` / `[city] name` (autogenerated; uses slug as id);
    # older hand-crafted designs used `[design] id` / `[design] name`.
    city = doc.get("city", {})
    design_meta = doc.get("design", {})
    slug = city.get("slug") or design_meta.get("id", "unknown")
    name = (
        design_meta.get("name")
        or city.get("name")
        or (city.get("slug") or "").title()
        or "unnamed"
    )

    stations = doc.get("stations", [])
    lines = doc.get("lines", [])
    fleets = doc.get("fleets", [])
    depots = doc.get("depots", [])

    # Route length: prefer the rust-emitted `length_m` per line; fall
    # back to summing inline `distance_from_prev_m` for the older
    # nested-stations schema.
    route_m = 0.0
    for line in lines:
        if "length_m" in line:
            route_m += float(line["length_m"])
        else:
            for st in line.get("stations", []):
                route_m += float(st.get("distance_from_prev_m", 0))
        if line.get("shape") == "ring" or line.get("is_ring"):
            route_m += float(line.get("ring_wrap_length_m", 0))
    route_km = route_m / 1000.0

    # Fleet totals. The rust emitter writes peak/spare/cold-reserve
    # explicitly; older designs only had `trainset_count` (= total).
    # Use `peak_count` when present, fall back to `trainset_count`.
    revenue = sum(
        int(f.get("peak_count") or f.get("trainset_count", 0))
        for f in fleets
    )
    spare = sum(int(f.get("spare_count", 0)) for f in fleets)
    cold = sum(int(f.get("cold_reserve_count", 0)) for f in fleets)

    # Interchange count: prefer the explicit archetype tag emitted by
    # `osr-design` (covers both `interchange` and `interchange-elevated`).
    # Fall back to multi-line-membership counting for older designs
    # whose stations carried a `lines` array.
    explicit_groups = {
        s.get("junction_group") for s in stations
        if s.get("junction_group") is not None
    }
    interchange_count = len(explicit_groups)
    if interchange_count == 0:
        interchange_count = sum(
            1 for s in stations
            if s.get("archetype") in ("interchange", "interchange-elevated")
        )
    if interchange_count == 0:
        appearances: dict[str, int] = {}
        for line in lines:
            for st in line.get("stations", []):
                appearances[st["id"]] = appearances.get(st["id"], 0) + 1
        interchange_count = sum(1 for v in appearances.values() if v > 1)

    # Peak headway: smallest `headway_min` across all fleets' schedules.
    # Auto-generated fleets carry a 3-min peak by default; honour the
    # design's value when present.
    peak_headway = math.inf
    for f in fleets:
        for w in f.get("schedule", []):
            peak_headway = min(peak_headway, float(w.get("headway_min", math.inf)))
    if peak_headway == math.inf:
        peak_headway = 3.0

    return DesignStats(
        slug=slug,
        name=name,
        line_count=len(lines),
        unique_station_count=len(stations),
        route_km=route_km,
        revenue_fleet=revenue,
        spare_fleet=spare,
        cold_reserve_fleet=cold,
        total_fleet=revenue + spare + cold,
        depot_count=len(depots),
        interchange_count=interchange_count,
        peak_headway_min=peak_headway,
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="osr_scenario.stats",
        description="Compute summary stats for a city design.toml.",
    )
    ap.add_argument("--design", type=Path, default=None)
    ap.add_argument(
        "--format",
        choices=["markdown", "plain"],
        default="plain",
    )
    args = ap.parse_args(argv)
    if args.design is None:
        args.design = _find_repo_root() / "designs/west-asia/Iraq/Samawah/design.toml"
    s = compute_stats(args.design)
    if args.format == "markdown":
        print(s.as_markdown_table())
    else:
        print(f"design:           {s.name}")
        print(f"lines:            {s.line_count}")
        print(f"unique stations:  {s.unique_station_count}")
        print(f"interchanges:     {s.interchange_count}")
        print(f"route:            {s.route_km:.1f} km")
        print(f"revenue fleet:    {s.revenue_fleet}")
        print(f"spare + reserve:  {s.spare_fleet + s.cold_reserve_fleet}")
        print(f"depots:           {s.depot_count}")
        print(f"peak headway:     {s.peak_headway_min:.0f} min")
    return 0


def _find_repo_root() -> Path:
    cur = Path(__file__).resolve()
    for parent in cur.parents:
        if (parent / "Cargo.toml").exists():
            return parent
    return Path.cwd()


if __name__ == "__main__":
    raise SystemExit(main())
