#!/usr/bin/env python3
"""Generate the concise public overview from canonical repository metrics."""

from __future__ import annotations

import argparse
import html
import json
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "docs/brochures/open-source-rail-overview.html"
MARKETING_MANIFEST = REPO_ROOT / "marketing/manifest.json"
TRAINSET_COST = (
    REPO_ROOT / "mechanical-py/catalog/buildable-trainset/trainset-build-cost.json"
)
REFERENCED_ASSETS = (
    REPO_ROOT / "docs/assets/solar-metro-trainset.png",
    REPO_ROOT / "docs/screenshots/city-studio/gui-acceptance.png",
    REPO_ROOT / "docs/screenshots/civil/bonsai-ifc4x3-civil-coordination.png",
)


def compact_usd(value: float) -> str:
    if value >= 1_000_000:
        return f"${value / 1_000_000:.2f}M"
    return f"${value / 1_000:.0f}k"


def render() -> str:
    missing = [path for path in REFERENCED_ASSETS if not path.is_file()]
    if missing:
        joined = ", ".join(str(path.relative_to(REPO_ROOT)) for path in missing)
        raise FileNotFoundError(f"missing overview asset(s): {joined}")
    marketing = json.loads(MARKETING_MANIFEST.read_text(encoding="utf-8"))
    trainset = json.loads(TRAINSET_COST.read_text(encoding="utf-8"))
    if marketing.get("marketing_focus") != "developing-world":
        raise ValueError("marketing manifest must declare developing-world focus")
    catalogue = int(marketing["catalogue_city_count"])
    cities = int(marketing["city_campaign_count"])
    countries = int(marketing["country_campaign_count"])
    targets = int(marketing["international_campaign_count"])
    excluded = int(marketing["excluded_from_marketing_count"])
    if catalogue - cities != excluded:
        raise ValueError("marketing catalogue exclusion counts do not reconcile")
    estimate = compact_usd(float(trainset["total_build_cost_usd"]))
    planning_unit = compact_usd(float(trainset["rounded_local_owner_unit_usd"]))
    values = {
        "catalogue": str(catalogue),
        "cities": str(cities),
        "countries": str(countries),
        "targets": str(targets),
        "estimate": estimate,
        "planning_unit": planning_unit,
    }
    values = {key: html.escape(value) for key, value in values.items()}
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenSourceRail — One-page overview</title>
  <style>
    @page {{ size: A4 landscape; margin: 9mm; }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; color: #10233d; background: #edf3f8; font: 10pt/1.35 "DejaVu Sans", Arial, sans-serif; }}
    main {{ width: 100%; min-height: 190mm; padding: 7mm; background: #f9fcff; border: 1px solid #c8d6e6; }}
    header {{ display: grid; grid-template-columns: 1.25fr 1fr; gap: 7mm; align-items: center; }}
    h1 {{ margin: 0; font-size: 29pt; line-height: 1; }}
    h2 {{ margin: 0 0 2mm; font-size: 13pt; }}
    p {{ margin: 0 0 2.5mm; }}
    .tag {{ display: inline-block; margin-bottom: 3mm; padding: 1.2mm 3mm; border-radius: 9mm; color: white; background: #0a6840; font-weight: 700; }}
    .hero {{ width: 100%; height: 64mm; object-fit: contain; background: white; border: 1px solid #c8d6e6; border-radius: 3mm; }}
    .metrics {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 3mm; margin: 5mm 0; }}
    .metric, .card {{ padding: 3mm; background: white; border: 1px solid #c8d6e6; border-radius: 2.5mm; }}
    .metric strong {{ display: block; color: #0a6840; font-size: 17pt; }}
    .metric span {{ color: #526277; font-size: 8pt; }}
    .content {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 4mm; }}
    ul {{ margin: 0; padding-left: 4.5mm; }}
    li {{ margin-bottom: 1.1mm; font-size: 8.7pt; }}
    .shots {{ display: grid; grid-template-columns: 1fr 1fr; gap: 2mm; }}
    .shots img {{ width: 100%; height: 37mm; object-fit: cover; border: 1px solid #c8d6e6; }}
    .foot {{ display: grid; grid-template-columns: 1.25fr 1fr; gap: 4mm; margin-top: 4mm; }}
    .small {{ color: #526277; font-size: 7.6pt; }}
    a {{ color: #0757a0; }}
  </style>
</head>
<body>
<main>
  <!-- Generated by scripts/generate-introduction-brochure.py; do not hand-edit. -->
  <header>
    <div>
      <span class="tag">Open urban-rail engineering for developing countries</span>
      <h1>OpenSourceRail</h1>
      <p><strong>One deterministic workspace for city design, GIS, service planning, CAD/IFC, simulation, operations and assurance.</strong></p>
      <p>OpenSourceRail turns reviewable source inputs into Git-versioned network, fleet, energy, civil, cost and operating evidence. It is an open planning and engineering baseline—not a feasibility study, supplier bid, safety certificate or authority approval.</p>
    </div>
    <img class="hero" src="../assets/solar-metro-trainset.png" alt="OpenSourceRail light-metro reference trainset">
  </header>

  <section class="metrics">
    <div class="metric"><strong>{values['cities']}</strong><span>developing-world city campaigns</span></div>
    <div class="metric"><strong>{values['countries']}</strong><span>countries in the evidence scope</span></div>
    <div class="metric"><strong>{values['targets']}</strong><span>international research, funding and sector targets</span></div>
    <div class="metric"><strong>{values['planning_unit']}</strong><span>3-car LM3 planning unit; generated build estimate {values['estimate']}</span></div>
  </section>

  <section class="content">
    <div class="card">
      <h2>Design and regenerate</h2>
      <ul>
        <li>Interactively edit lines, stations, alignments, demand and line/day/hour service.</li>
        <li>Generate GIS, OSR-ALN, IFC4.3, IDS/BCF, CAD quantities, costs and city packages.</li>
        <li>Store immutable revisions, semantic comparisons and approvals in Git.</li>
        <li>Propagate controlled geometry and rate changes through city and portfolio calculations.</li>
      </ul>
    </div>
    <div class="card">
      <h2>Simulate and operate</h2>
      <ul>
        <li>Run deterministic train, station, energy, wayside, point/crossing and depot software together.</li>
        <li>Use one Workbench for City Studio, simulation, OCC training and Ops Core.</li>
        <li>Exercise QA gates, manufacturing, maintenance, incidents and evidence persistence.</li>
        <li>Run pinned browser acceptance and repository drift checks before review.</li>
      </ul>
    </div>
    <div class="shots">
      <img src="../screenshots/city-studio/gui-acceptance.png" alt="City Studio deterministic browser acceptance">
      <img src="../screenshots/civil/bonsai-ifc4x3-civil-coordination.png" alt="Bonsai IFC4.3 civil coordination model">
    </div>
  </section>

  <section class="foot">
    <div class="card">
      <h2>Buildable, inspectable system</h2>
      <p>Reference packages cover modular rolling stock, simplified fasteners and fixtures, stations, track and civil works, battery traction and renewable charging, embedded host roles, operations procedures and machine-checkable safety evidence.</p>
      <p class="small">The engineering catalogue contains {values['catalogue']} models. European comparison designs are retained for technical inspection but excluded from public evidence totals, examples and outreach packages.</p>
    </div>
    <div class="card">
      <h2>Review or collaborate</h2>
      <p><a href="https://github.com/modernecotech/OpenSourceRail">github.com/modernecotech/OpenSourceRail</a></p>
      <p>Government, municipality, university, research, development-finance, operator and open-source collaboration packages are generated from the same evidence.</p>
      <p><strong>Contact:</strong> hayder@modernecotech.com</p>
    </div>
  </section>
</main>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale: {OUTPUT.relative_to(REPO_ROOT)}")
            return 1
        print(f"current: {OUTPUT.relative_to(REPO_ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", dir=OUTPUT.parent, delete=False, encoding="utf-8"
    ) as handle:
        handle.write(expected)
        temporary = Path(handle.name)
    temporary.replace(OUTPUT)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
