#!/usr/bin/env python3
"""Generate the developing-world capital summary from current city models."""

from __future__ import annotations

import argparse
import runpy
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "design-py/src"))

from osr_scenario.capital import (  # noqa: E402
    NATIONAL_FACTORY_PER_VEHICLE_USD,
    aggregate_breakdowns,
    foreign_turnkey_cases,
    funding_plan,
)
from osr_scenario.network_readme import _load_country_finance  # noqa: E402

OUTPUT = REPO_ROOT / "docs/portfolio-summary.md"
DEVELOPING_WORLD_REGIONS = {
    "central-africa",
    "east-africa",
    "latin-america",
    "north-africa",
    "south-africa",
    "south-asia",
    "southeast-asia",
    "west-africa",
    "west-asia",
}


def money(value: float) -> str:
    if abs(value) >= 1_000_000_000_000:
        return f"${value / 1_000_000_000_000:,.2f}T"
    if abs(value) >= 1_000_000_000:
        return f"${value / 1_000_000_000:,.2f}B"
    return f"${value / 1_000_000:,.1f}M"


def build_summary() -> str:
    load_city = runpy.run_path(
        str(REPO_ROOT / "scripts/generate-national-briefs.py")
    )["load_city"]
    grouped: dict[str, list[object]] = defaultdict(list)
    city_count = 0
    for path in sorted((REPO_ROOT / "designs").glob("*/*/*/design.toml")):
        region = path.relative_to(REPO_ROOT / "designs").parts[0]
        if region not in DEVELOPING_WORLD_REGIONS:
            continue
        code, city = load_city(path)
        grouped[code].append(city)
        city_count += 1

    totals = {
        key: 0.0
        for key in (
            "total", "external", "local", "bond", "equity", "annual_total",
            "annual_external", "annual_local", "foreign_total", "foreign_external",
            "external_saved", "interest_saved", "lifetime_saved",
        )
    }
    imported_shares: list[float] = []
    for code, cities in grouped.items():
        factory = max(city.vehicle_modules for city in cities) * NATIONAL_FACTORY_PER_VEHICLE_USD
        national = aggregate_breakdowns(
            [city.breakdown for city in cities], national_factory_usd=factory
        )
        plan = funding_plan(national, _load_country_finance(code))
        comparison = foreign_turnkey_cases(national, plan)["default"]
        totals["total"] += national.total_usd
        totals["external"] += national.imported_usd
        totals["local"] += national.local_usd
        totals["bond"] += plan.local_bond_usd
        totals["equity"] += plan.local_equity_usd
        totals["annual_total"] += national.total_usd / plan.construction_years
        totals["annual_external"] += plan.annual_external_capital_draw_usd
        totals["annual_local"] += plan.annual_local_capital_draw_usd
        totals["foreign_total"] += comparison.foreign_total_usd
        totals["foreign_external"] += comparison.foreign_external_usd
        totals["external_saved"] += comparison.external_capital_avoided_usd
        totals["interest_saved"] += comparison.external_interest_avoided_usd
        totals["lifetime_saved"] += comparison.lifetime_external_financing_avoided_usd
        imported_shares.extend(city.breakdown.imported_share for city in cities)

    imported_pct = totals["external"] / totals["total"]
    reduction = totals["external_saved"] / totals["foreign_external"]
    out = [
        "# Portfolio capital summary",
        "",
        "<!-- Generated by scripts/generate-portfolio-summary.py; do not hand-edit. -->",
        "",
        "This is the current aggregation of generated city models in the developing-world "
        "evidence scope, including one shared trainset factory per country. European "
        "comparison designs remain in the engineering catalogue but are excluded here. "
        "This is a planning screen, not a financing commitment, audited origin "
        "declaration, supplier quotation, or vendor bid.",
        "",
        f"| {city_count}-city / {len(grouped)}-country catalogue | Planning value | Annual construction draw across country programmes |",
        "|---|---:|---:|",
        f"| External capital for imported components and machinery | **{money(totals['external'])} ({imported_pct:.1%})** | **{money(totals['annual_external'])}/year** |",
        f"| Local capital for domestic value | **{money(totals['local'])} ({1-imported_pct:.1%})** | **{money(totals['annual_local'])}/year** |",
        f"| of which planned local-currency bond issuance | {money(totals['bond'])} | — |",
        f"| local public equity / other domestic funding | {money(totals['equity'])} | — |",
        f"| **Total national programmes** | **{money(totals['total'])}** | **{money(totals['annual_total'])}/year** |",
        "",
        "## Foreign-turnkey sensitivity",
        "",
        "The default comparison uses the controlled 2.0× total-cost and 90% "
        "external-capital assumptions. Country financing schedules and rates remain "
        "unchanged between cases.",
        "",
        "| Measure | Current aggregate |",
        "|---|---:|",
        f"| Equivalent foreign-turnkey total | {money(totals['foreign_total'])} |",
        f"| Foreign-turnkey external capital | {money(totals['foreign_external'])} |",
        f"| OSR external capital avoided | **{money(totals['external_saved'])} ({reduction:.1%})** |",
        f"| External interest avoided | **{money(totals['interest_saved'])}** |",
        f"| External capital plus interest avoided | **{money(totals['lifetime_saved'])}** |",
        "",
        f"Individual city imported shares range from {min(imported_shares):.1%} to "
        f"{max(imported_shares):.1%}. Replace the imported shares, cost multiplier and "
        "financing terms with audited supplier capability, normalized bids and signed "
        "lender terms before an investment decision.",
        "",
        "Regenerate with `python3 scripts/generate-portfolio-summary.py` after city costs "
        "or country financing inputs change.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = build_summary()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print(f"current: {OUTPUT.relative_to(REPO_ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=OUTPUT.parent, delete=False, encoding="utf-8") as handle:
        handle.write(expected)
        temporary = Path(handle.name)
    temporary.replace(OUTPUT)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
